apiVersion: v1
kind: Secret
metadata:
  name: dynatrace-gcp-function-secret
  namespace: dynatrace
type: "kubernetes.io/storageos"
data:
  access-key: {{ .Values.dynatraceAccessKey | b64enc | quote }}
  url: {{ .Values.dynatraceUrl | b64enc | quote }}
  log-ingest-url: {{ .Values.dynatraceLogIngestUrl | b64enc | quote }}