#     Copyright 2020 Dynatrace LLC
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  "annotations": {
    "iam.gke.io/gcp-service-account" : {{ .Values.serviceAccount }}@{{ .Values.gcpProjectId }}.iam.gserviceaccount.com
  }
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-gcp-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: dynatrace-gcp-monitor
spec:
  selector:
    matchLabels:
      app: dynatrace-gcp-monitor
  replicas: 1
  template:
    metadata:
      labels:
        app: dynatrace-gcp-monitor
      annotations:
        "version" : "1"
        checksum/config: {{ include (print $.Template.BasePath "/function-config.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/function-secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      automountServiceAccountToken: false
      {{- if or (eq .Values.deploymentType "metrics") (eq .Values.deploymentType "all") }}
      volumes:
      - name: gcp-config
        configMap:
          name: dynatrace-gcp-monitor-config
          items:
          - key: GCP_SERVICES_YAML
            path: "gcp_services.yaml"
          {{- if eq (lower .Values.metricAutodiscovery) "true" }}
          - key: AUTODISCOVERY_RESOURCES_YAML
            path: "autodiscovery-config.yaml"
          - key: AUTODISCOVERY_METRIC_BLOCK_LIST_YAML
            path: "autodiscovery-block-list.yaml"
          {{- end }}
      {{- end }}
      {{- if (.Values.imagePullSecrets) }}      
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}      
      containers:
      {{- if or (eq .Values.deploymentType "metrics") (eq .Values.deploymentType "all") }}
      - image: {{ .Values.dockerImage | quote }}
        name: dynatrace-gcp-monitor-metrics
        imagePullPolicy: Always
        env:
        - name: OPERATION_MODE
          value: Metrics
        - name: PRINT_METRIC_INGEST_INPUT
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: PRINT_METRIC_INGEST_INPUT
        - name: METRIC_AUTODISCOVERY
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: METRIC_AUTODISCOVERY
        - name: GCP_PROJECT
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: GCP_PROJECT
        - name: REQUIRE_VALID_CERTIFICATE
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: REQUIRE_VALID_CERTIFICATE
        - name: SERVICE_USAGE_BOOKING
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: SERVICE_USAGE_BOOKING
        {{- if (.Values.useProxy) }}
        - name: USE_PROXY
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: USE_PROXY
        - name: HTTP_PROXY
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: HTTP_PROXY
        - name: HTTPS_PROXY
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: HTTPS_PROXY
        {{- end }}
        - name: DYNATRACE_ACCESS_KEY_SECRET_NAME
          value: DYNATRACE_ACCESS_KEY
        - name: DYNATRACE_URL_SECRET_NAME
          value: DYNATRACE_URL
        - name: DYNATRACE_URL
          valueFrom:
            secretKeyRef:
              name: dynatrace-gcp-monitor-secret
              key: url
        - name: DYNATRACE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: dynatrace-gcp-monitor-secret
              key: access-key
        - name: SELF_MONITORING_ENABLED
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: SELF_MONITORING_ENABLED
        - name: QUERY_INTERVAL_MIN
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: QUERY_INTERVAL_MIN
        {{- if eq (lower .Values.metricAutodiscovery) "true" }}
        - name: AUTODISCOVERY_QUERY_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: AUTODISCOVERY_QUERY_INTERVAL
        - name: AUTODISCOVERY_INCLUDE_ALPHA_METRICS
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: AUTODISCOVERY_INCLUDE_ALPHA_METRICS
        {{- end }}
        - name: HEALTH_CHECK_PORT
          value: "8080"
        - name: SCOPING_PROJECT_SUPPORT_ENABLED
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: SCOPING_PROJECT_SUPPORT_ENABLED
        - name: EXCLUDED_PROJECTS
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: EXCLUDED_PROJECTS
        - name: EXCLUDED_PROJECTS_BY_PREFIX
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: EXCLUDED_PROJECTS_BY_PREFIX

        - name:   KEEP_REFRESHING_EXTENSIONS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key:   KEEP_REFRESHING_EXTENSIONS_CONFIG
        volumeMounts:
        - mountPath: /code/config/activation
          readOnly: true
          name: gcp-config
        resources: {{- toYaml .Values.metricResources | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 120
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 120
        securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            runAsUser: 1001
      {{- end }}
      {{- if or (eq .Values.deploymentType "logs") (eq .Values.deploymentType "all") }}
      - image: {{ .Values.dockerImage | quote }}
        name: dynatrace-gcp-monitor-logs
        imagePullPolicy: Always
        env:
        - name: OPERATION_MODE
          value: Logs
        - name: GCP_PROJECT
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: GCP_PROJECT
        - name: LOGS_SUBSCRIPTION_ID
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: LOGS_SUBSCRIPTION_ID
        - name: DYNATRACE_LOG_INGEST_CONTENT_MAX_LENGTH
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: DYNATRACE_LOG_INGEST_CONTENT_MAX_LENGTH
        - name: DYNATRACE_LOG_INGEST_ATTRIBUTE_VALUE_MAX_LENGTH
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: DYNATRACE_LOG_INGEST_ATTRIBUTE_VALUE_MAX_LENGTH
        - name: DYNATRACE_LOG_INGEST_REQUEST_MAX_EVENTS
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: DYNATRACE_LOG_INGEST_REQUEST_MAX_EVENTS
        - name: DYNATRACE_LOG_INGEST_REQUEST_MAX_SIZE
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: DYNATRACE_LOG_INGEST_REQUEST_MAX_SIZE
        - name: DYNATRACE_LOG_INGEST_SENDING_WORKER_EXECUTION_PERIOD
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: DYNATRACE_LOG_INGEST_SENDING_WORKER_EXECUTION_PERIOD
        - name: DYNATRACE_TIMEOUT_SECONDS
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: DYNATRACE_TIMEOUT_SECONDS
        - name: PROCESSING_WORKERS
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: PROCESSING_WORKERS
        - name: PROCESSING_WORKER_PULL_REQUEST_MAX_MESSAGES
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: PROCESSING_WORKER_PULL_REQUEST_MAX_MESSAGES
        - name: CLOUD_LOG_FORWARDER
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: CLOUD_LOG_FORWARDER
        - name: REQUIRE_VALID_CERTIFICATE
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: REQUIRE_VALID_CERTIFICATE
        - name: DYNATRACE_ACCESS_KEY_SECRET_NAME
          value: DYNATRACE_ACCESS_KEY
        - name: DYNATRACE_LOG_INGEST_URL_SECRET_NAME
          value: DYNATRACE_LOG_INGEST_URL
        - name: DYNATRACE_LOG_INGEST_URL
          valueFrom:
            secretKeyRef:
              name: dynatrace-gcp-monitor-secret
              key: log-ingest-url
        - name: DYNATRACE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: dynatrace-gcp-monitor-secret
              key: access-key
        - name: SELF_MONITORING_ENABLED
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: SELF_MONITORING_ENABLED
        {{- if (.Values.useProxy) }}
        - name: USE_PROXY
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              key: USE_PROXY
        # the PubSub uses gPRC so both variables have to be set
        - name: HTTP_PROXY
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              {{- if .Values.httpProxy }}
              key: HTTP_PROXY
              {{- else }}
              key: HTTPS_PROXY
              {{- end }}
        - name: HTTPS_PROXY
          valueFrom:
            configMapKeyRef:
              name: dynatrace-gcp-monitor-config
              {{- if .Values.httpsProxy }}
              key: HTTPS_PROXY
              {{- else }}
              key: HTTP_PROXY
              {{- end }}
        - name: NO_PROXY
          value: {{ template "noProxyUrls" . }}
        {{- end }}
        - name: HEALTH_CHECK_PORT
          value: "8081"
        resources: {{- toYaml .Values.logResources | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          timeoutSeconds: 60
        startupProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          timeoutSeconds: 10
          failureThreshold: 2
        securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            runAsUser: 1001          
      {{- end }}
