id: assistant_action_project
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Assistant Action Project
gcp:
- service: assistant_action_project
  featureSet: default
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    key: gcp.project.id
  metrics:
  - value: actions.googleapis.com/smarthome_action/num_active_users
    key: cloud.gcp.actions_googleapis_com.smarthome_action.num_active_users
    type: gauge
    name: Daily active users
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: metric.labels.device_type
    - value: metric.labels.locale
    - value: metric.labels.trait
  - value: actions.googleapis.com/smarthome_action/request_count
    key: cloud.gcp.actions_googleapis_com.smarthome_action.request_count
    type: count,delta
    name: Request count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.device_type
    - value: metric.labels.status
    - value: metric.labels.trait
    - value: metric.labels.is_local
    - value: metric.labels.execution_type
  - value: actions.googleapis.com/smarthome_action/request_latencies
    key: cloud.gcp.actions_googleapis_com.smarthome_action.request_latencies
    type: gauge
    name: Request latencies
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: ms
    dimensions:
    - value: metric.labels.device_type
    - value: metric.labels.status
    - value: metric.labels.trait
    - value: metric.labels.is_local
    - value: metric.labels.execution_type
  - value: actions.googleapis.com/smarthome_action/seven_day_active_users
    key: cloud.gcp.actions_googleapis_com.smarthome_action.seven_day_active_users
    type: gauge
    name: 7 day active users
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: metric.labels.device_type
    - value: metric.labels.locale
    - value: metric.labels.trait
  - value: actions.googleapis.com/smarthome_action/twenty_eight_day_active_users
    key: cloud.gcp.actions_googleapis_com.smarthome_action.twenty_eight_day_active_users
    type: gauge
    name: 28 day active users
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: metric.labels.device_type
    - value: metric.labels.locale
    - value: metric.labels.trait
