id: bigquery_biengine_model
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
- id: filter_conditions
  displayName: Metric query filter for which metrics should be queried
  type: variables
technology:
  name: Google Cloud BigQuery BI Engine Model
gcp:
- service: bigquery_biengine_model
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: label:resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: label:resource.labels.project_id
    key: gcp.project.id
  - value: label:resource.labels.location
    key: location
    compatibilityModeOnly: true
  - value: label:resource.labels.location
    key: gcp.region
  - value: label:resource.labels.model_id
    key: model_id
    compatibilityModeOnly: true
  - value: label:resource.labels.model_id
    key: gcp.instance.id
  metrics:
  - value: metric:bigquerybiengine.googleapis.com/model/inflight_requests
    key: cloud.gcp.bigquerybiengine_googleapis_com.model.inflight_requests
    type: gauge
    name: Inflight requests
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: metric:bigquerybiengine.googleapis.com/model/request_count
    key: cloud.gcp.bigquerybiengine_googleapis_com.model.request_count
    type: count,delta
    name: Request count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.cache_miss
      key: cache_miss
    - value: label:metric.labels.status
      key: status
    - value: label:metric.labels.execution_mode
      key: execution_mode
  - value: metric:bigquerybiengine.googleapis.com/model/request_latencies
    key: cloud.gcp.bigquerybiengine_googleapis_com.model.request_latencies
    type: gauge
    name: Request execution times
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: GAUGE
      unit: ms
    dimensions:
    - value: label:metric.labels.cache_miss
      key: cache_miss
    - value: label:metric.labels.status
      key: status
    - value: label:metric.labels.execution_mode
      key: execution_mode
