id: bigquery_biengine_model
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google Cloud BigQuery BI Engine Model
gcp:
- service: bigquery_biengine_model
  featureSet: default
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.location
    id: location
  - value: resource.labels.model_id
    id: model_id
  metrics:
  - value: bigquerybiengine.googleapis.com/model/inflight_requests
    id: cloud.gcp.bigquerybiengine_googleapis_com.model.inflight_requests
    type: gauge
    name: Inflight requests
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: bigquerybiengine.googleapis.com/model/request_count
    id: cloud.gcp.bigquerybiengine_googleapis_com.model.request_count
    type: count,delta
    name: Request count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.cache_miss
    - value: metric.labels.status
    - value: metric.labels.execution_mode
  - value: bigquerybiengine.googleapis.com/model/request_latencies
    id: cloud.gcp.bigquerybiengine_googleapis_com.model.request_latencies
    type: gauge
    name: Request execution times
    unit: ms
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.cache_miss
    - value: metric.labels.status
    - value: metric.labels.execution_mode
