id: cloud_dataproc_cluster
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
- id: filter_conditions
  displayName: Metric query filter for which metrics should be queried
  type: variables
technology:
  name: Google Cloud Dataproc Cluster
gcp:
- service: cloud_dataproc_cluster
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: label:resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: label:resource.labels.project_id
    key: gcp.project.id
  - value: label:resource.labels.cluster_name
    key: cluster_name
    compatibilityModeOnly: false
  - value: label:resource.labels.cluster_name
    key: gcp.instance.name
  - value: label:resource.labels.cluster_uuid
    key: cluster_uuid
  - value: label:resource.labels.region
    key: region
    compatibilityModeOnly: true
  - value: label:resource.labels.region
    key: gcp.region
  metrics:
  - value: metric:dataproc.googleapis.com/cluster/hdfs/datanodes
    key: cloud.gcp.dataproc_googleapis_com.cluster.hdfs.datanodes
    type: gauge
    name: HDFS DataNodes
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.status
      key: status
  - value: metric:dataproc.googleapis.com/cluster/hdfs/storage_capacity
    key: cloud.gcp.dataproc_googleapis_com.cluster.hdfs.storage_capacity
    type: gauge
    name: HDFS capacity
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: GiBy
    dimensions:
    - value: label:metric.labels.status
      key: status
  - value: metric:dataproc.googleapis.com/cluster/hdfs/storage_utilization
    key: cloud.gcp.dataproc_googleapis_com.cluster.hdfs.storage_utilization
    type: gauge
    name: HDFS storage utilization
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: metric:dataproc.googleapis.com/cluster/hdfs/unhealthy_blocks
    key: cloud.gcp.dataproc_googleapis_com.cluster.hdfs.unhealthy_blocks
    type: gauge
    name: Unhealthy HDFS blocks by status
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.status
      key: status
  - value: metric:dataproc.googleapis.com/cluster/job/completion_time
    key: cloud.gcp.dataproc_googleapis_com.cluster.job.completion_time
    type: gauge
    name: Job duration
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: s
    dimensions:
    - value: label:metric.labels.job_type
      key: job_type
  - value: metric:dataproc.googleapis.com/cluster/job/duration
    key: cloud.gcp.dataproc_googleapis_com.cluster.job.duration
    type: gauge
    name: Job state duration
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: s
    dimensions:
    - value: label:metric.labels.job_type
      key: job_type
    - value: label:metric.labels.state
      key: state
  - value: metric:dataproc.googleapis.com/cluster/job/failed_count
    key: cloud.gcp.dataproc_googleapis_com.cluster.job.failed_count
    type: count,delta
    name: Failed jobs
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.error_type
      key: error_type
    - value: label:metric.labels.job_type
      key: job_type
  - value: metric:dataproc.googleapis.com/cluster/job/running_count
    key: cloud.gcp.dataproc_googleapis_com.cluster.job.running_count
    type: gauge
    name: Running jobs
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.job_type
      key: job_type
  - value: metric:dataproc.googleapis.com/cluster/job/submitted_count
    key: cloud.gcp.dataproc_googleapis_com.cluster.job.submitted_count
    type: count,delta
    name: Submitted jobs
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.job_type
      key: job_type
  - value: metric:dataproc.googleapis.com/cluster/operation/completion_time
    key: cloud.gcp.dataproc_googleapis_com.cluster.operation.completion_time
    type: gauge
    name: Operation duration
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: s
    dimensions:
    - value: label:metric.labels.operation_type
      key: operation_type
  - value: metric:dataproc.googleapis.com/cluster/operation/duration
    key: cloud.gcp.dataproc_googleapis_com.cluster.operation.duration
    type: gauge
    name: Operation state duration
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: s
    dimensions:
    - value: label:metric.labels.operation_type
      key: operation_type
    - value: label:metric.labels.state
      key: state
  - value: metric:dataproc.googleapis.com/cluster/operation/failed_count
    key: cloud.gcp.dataproc_googleapis_com.cluster.operation.failed_count
    type: count,delta
    name: Failed operations
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.error_type
      key: error_type
    - value: label:metric.labels.operation_type
      key: operation_type
  - value: metric:dataproc.googleapis.com/cluster/operation/running_count
    key: cloud.gcp.dataproc_googleapis_com.cluster.operation.running_count
    type: gauge
    name: Running operations
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.operation_type
      key: operation_type
  - value: metric:dataproc.googleapis.com/cluster/operation/submitted_count
    key: cloud.gcp.dataproc_googleapis_com.cluster.operation.submitted_count
    type: count,delta
    name: Submitted operations
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.operation_type
      key: operation_type
  - value: metric:dataproc.googleapis.com/cluster/yarn/allocated_memory_percentage
    key: cloud.gcp.dataproc_googleapis_com.cluster.yarn.allocated_memory_percentage
    type: gauge
    name: YARN allocated memory percentage
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: metric:dataproc.googleapis.com/cluster/yarn/apps
    key: cloud.gcp.dataproc_googleapis_com.cluster.yarn.apps
    type: gauge
    name: YARN active applications
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.status
      key: status
  - value: metric:dataproc.googleapis.com/cluster/yarn/containers
    key: cloud.gcp.dataproc_googleapis_com.cluster.yarn.containers
    type: gauge
    name: YARN containers
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.status
      key: status
  - value: metric:dataproc.googleapis.com/cluster/yarn/memory_size
    key: cloud.gcp.dataproc_googleapis_com.cluster.yarn.memory_size
    type: gauge
    name: YARN memory size
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: GiBy
    dimensions:
    - value: label:metric.labels.status
      key: status
  - value: metric:dataproc.googleapis.com/cluster/yarn/nodemanagers
    key: cloud.gcp.dataproc_googleapis_com.cluster.yarn.nodemanagers
    type: gauge
    name: YARN NodeManagers
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.status
      key: status
  - value: metric:dataproc.googleapis.com/cluster/yarn/pending_memory_size
    key: cloud.gcp.dataproc_googleapis_com.cluster.yarn.pending_memory_size
    type: gauge
    name: YARN pending memory size
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: GiBy
    dimensions: []
  - value: metric:dataproc.googleapis.com/cluster/yarn/virtual_cores
    key: cloud.gcp.dataproc_googleapis_com.cluster.yarn.virtual_cores
    type: gauge
    name: YARN virtual cores
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.status
      key: status
