id: cloudtrace.googleapis.com_CloudtraceProject
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
- id: filter_conditions
  displayName: Metric query filter for which metrics should be queried
  type: variables
technology:
  name: Google Cloud Trace
gcp:
- service: cloudtrace.googleapis.com_CloudtraceProject
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: label:resource.labels.resource_container
    key: resource_container
  - value: label:resource.labels.location
    key: location
    compatibilityModeOnly: true
  - value: label:resource.labels.location
    key: gcp.region
  metrics:
  - value: metric:cloudtrace.googleapis.com/bigquery_export/exported_span_count
    key: cloud.gcp.cloudtrace_googleapis_com.bigquery_export.exported_span_count
    type: count,delta
    name: Spans Exported to BigQuery
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.status
      key: status
