id: cloud_tasks_queue
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
- id: filter_conditions
  displayName: Metric query filter for which metrics should be queried
  type: variables
technology:
  name: Amazon EC2 Instance (via GCP)
gcp:
- service: cloud_tasks_queue
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: label:resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: label:resource.labels.project_id
    key: gcp.project.id
  - value: label:resource.labels.queue_id
    key: queue_id
    compatibilityModeOnly: true
  - value: label:resource.labels.queue_id
    key: gcp.instance.id
  - value: label:resource.labels.target_type
    key: target_type
  metrics:
  - value: metric:cloudtasks.googleapis.com/api/request_count
    key: cloud.gcp.cloudtasks_googleapis_com.api.request_count
    type: count,delta
    name: API requests
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.api_method
      key: api_method
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:cloudtasks.googleapis.com/queue/depth
    key: cloud.gcp.cloudtasks_googleapis_com.queue.depth
    type: gauge
    name: Queue depth
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: metric:cloudtasks.googleapis.com/queue/task_attempt_count
    key: cloud.gcp.cloudtasks_googleapis_com.queue.task_attempt_count
    type: count,delta
    name: Task attempt count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:cloudtasks.googleapis.com/queue/task_attempt_delays
    key: cloud.gcp.cloudtasks_googleapis_com.queue.task_attempt_delays
    type: gauge
    name: Task attempt delays
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: ms
    dimensions: []
