id: cloudtrace.googleapis.com/CloudtraceProject
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud Trace
gcp:
- service: cloudtrace.googleapis.com/CloudtraceProject
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.resource_container
    id: resource_container
  - value: resource.labels.location
    id: location
  metrics:
  - value: cloudtrace.googleapis.com/bigquery_export/exported_span_count
    id: cloud.gcp.cloudtrace_googleapis_com.bigquery_export.exported_span_count
    type: count,delta
    name: Spans Exported to BigQuery
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.status
