id: cloud_dataproc_cluster
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud Dataproc Cluster
gcp:
- service: cloud_dataproc_cluster
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.cluster_name
    id: cluster_name
  - value: resource.labels.cluster_uuid
    id: cluster_uuid
  - value: resource.labels.region
    id: region
  metrics:
  - value: dataproc.googleapis.com/cluster/hdfs/datanodes
    id: cloud.gcp.dataproc_googleapis_com.cluster.hdfs.datanodes
    type: gauge
    name: HDFS DataNodes
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.status
  - value: dataproc.googleapis.com/cluster/hdfs/storage_capacity
    id: cloud.gcp.dataproc_googleapis_com.cluster.hdfs.storage_capacity
    type: gauge
    name: HDFS capacity
    unit: GiBy
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.status
  - value: dataproc.googleapis.com/cluster/hdfs/storage_utilization
    id: cloud.gcp.dataproc_googleapis_com.cluster.hdfs.storage_utilization
    type: gauge
    name: HDFS storage utilization
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: dataproc.googleapis.com/cluster/hdfs/unhealthy_blocks
    id: cloud.gcp.dataproc_googleapis_com.cluster.hdfs.unhealthy_blocks
    type: gauge
    name: Unhealthy HDFS blocks by status
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.status
  - value: dataproc.googleapis.com/cluster/job/completion_time
    id: cloud.gcp.dataproc_googleapis_com.cluster.job.completion_time
    type: gauge
    name: Job duration
    unit: s
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.job_type
  - value: dataproc.googleapis.com/cluster/job/duration
    id: cloud.gcp.dataproc_googleapis_com.cluster.job.duration
    type: gauge
    name: Job state duration
    unit: s
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.job_type
    - value: metric.labels.state
  - value: dataproc.googleapis.com/cluster/job/failed_count
    id: cloud.gcp.dataproc_googleapis_com.cluster.job.failed_count
    type: count,delta
    name: Failed jobs
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.error_type
    - value: metric.labels.job_type
  - value: dataproc.googleapis.com/cluster/job/running_count
    id: cloud.gcp.dataproc_googleapis_com.cluster.job.running_count
    type: gauge
    name: Running jobs
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.job_type
  - value: dataproc.googleapis.com/cluster/job/submitted_count
    id: cloud.gcp.dataproc_googleapis_com.cluster.job.submitted_count
    type: count,delta
    name: Submitted jobs
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.job_type
  - value: dataproc.googleapis.com/cluster/operation/completion_time
    id: cloud.gcp.dataproc_googleapis_com.cluster.operation.completion_time
    type: gauge
    name: Operation duration
    unit: s
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.operation_type
  - value: dataproc.googleapis.com/cluster/operation/duration
    id: cloud.gcp.dataproc_googleapis_com.cluster.operation.duration
    type: gauge
    name: Operation state duration
    unit: s
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.operation_type
    - value: metric.labels.state
  - value: dataproc.googleapis.com/cluster/operation/failed_count
    id: cloud.gcp.dataproc_googleapis_com.cluster.operation.failed_count
    type: count,delta
    name: Failed operations
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.error_type
    - value: metric.labels.operation_type
  - value: dataproc.googleapis.com/cluster/operation/running_count
    id: cloud.gcp.dataproc_googleapis_com.cluster.operation.running_count
    type: gauge
    name: Running operations
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.operation_type
  - value: dataproc.googleapis.com/cluster/operation/submitted_count
    id: cloud.gcp.dataproc_googleapis_com.cluster.operation.submitted_count
    type: count,delta
    name: Submitted operations
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.operation_type
  - value: dataproc.googleapis.com/cluster/yarn/allocated_memory_percentage
    id: cloud.gcp.dataproc_googleapis_com.cluster.yarn.allocated_memory_percentage
    type: gauge
    name: YARN allocated memory percentage
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: dataproc.googleapis.com/cluster/yarn/apps
    id: cloud.gcp.dataproc_googleapis_com.cluster.yarn.apps
    type: gauge
    name: YARN active applications
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.status
  - value: dataproc.googleapis.com/cluster/yarn/containers
    id: cloud.gcp.dataproc_googleapis_com.cluster.yarn.containers
    type: gauge
    name: YARN containers
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.status
  - value: dataproc.googleapis.com/cluster/yarn/memory_size
    id: cloud.gcp.dataproc_googleapis_com.cluster.yarn.memory_size
    type: gauge
    name: YARN memory size
    unit: GiBy
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.status
  - value: dataproc.googleapis.com/cluster/yarn/nodemanagers
    id: cloud.gcp.dataproc_googleapis_com.cluster.yarn.nodemanagers
    type: gauge
    name: YARN NodeManagers
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.status
  - value: dataproc.googleapis.com/cluster/yarn/pending_memory_size
    id: cloud.gcp.dataproc_googleapis_com.cluster.yarn.pending_memory_size
    type: gauge
    name: YARN pending memory size
    unit: GiBy
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: dataproc.googleapis.com/cluster/yarn/virtual_cores
    id: cloud.gcp.dataproc_googleapis_com.cluster.yarn.virtual_cores
    type: gauge
    name: YARN virtual cores
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.status
