id: consumer_quota
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
- id: filter_conditions
  displayName: Metric query filter for which metrics should be queried
  type: variables
technology:
  name: Google Consumer Quota
gcp:
- service: consumer_quota
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: label:resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: label:resource.labels.project_id
    key: gcp.project.id
  - value: label:resource.labels.service
    key: service
  - value: label:resource.labels.location
    key: location
    compatibilityModeOnly: true
  - value: label:resource.labels.location
    key: gcp.region
  metrics:
  - value: metric:serviceruntime.googleapis.com/quota/allocation/usage
    key: cloud.gcp.serviceruntime_googleapis_com.quota.allocation.usage
    type: gauge
    name: Allocation quota usage
    gcpOptions:
      ingestDelay: ''
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.quota_metric
      key: quota_metric
  - value: metric:serviceruntime.googleapis.com/quota/exceeded
    key: cloud.gcp.serviceruntime_googleapis_com.quota.exceeded
    type: gauge
    name: Quota exceeded error
    gcpOptions:
      ingestDelay: ''
      samplePeriod: 60
      valueType: BOOL
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.limit_name
      key: limit_name
    - value: label:metric.labels.quota_metric
      key: quota_metric
  - value: metric:serviceruntime.googleapis.com/quota/limit
    key: cloud.gcp.serviceruntime_googleapis_com.quota.limit
    type: gauge
    name: Quota limit
    gcpOptions:
      ingestDelay: ''
      samplePeriod: 86400
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.limit_name
      key: limit_name
    - value: label:metric.labels.quota_metric
      key: quota_metric
  - value: metric:serviceruntime.googleapis.com/quota/rate/net_usage
    key: cloud.gcp.serviceruntime_googleapis_com.quota.rate.net_usage
    type: count,delta
    name: Rate quota usage
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.method
      key: method
    - value: label:metric.labels.quota_metric
      key: quota_metric
