id: gcp_datastore
version: 0.0.1
technology:
  name: Google Cloud Datastore
minDynatraceVersion: 1.199
gcp:
- service: datastore_request
  dimensions:
    - value: resource.labels.project_id
      dimension: project_id
    - value: resource.labels.module_id
      dimension: module_id
    - value: resource.labels.version_id
      dimension: version_id
  metrics:
    - value: datastore.googleapis.com/entity/write_sizes
      id: cloud.gcp.datastore_googleapis_com.entity.write_sizes
      type: gauge
      name: Sizes of written entities
      unit: By
      gcpOptions:
        ingestDelay: 240s
        samplePeriod: 60s
        valueType: DISTRIBUTION
        metricKind: DELTA
      dimensions:
        - value: metric.labels.op
    - value: datastore.googleapis.com/api/request_count
      id: cloud.gcp.datastore_googleapis_com.api.request_count
      type: count,delta
      name: Requests
      unit: "1"
      gcpOptions:
        ingestDelay: 240s
        samplePeriod: 60s
        valueType: INT64
        metricKind: DELTA
      dimensions:
        - value: metric.labels.response_code
        - value: metric.labels.api_method
    - value: firestore.googleapis.com/api/request_count
      id: cloud.gcp.firestore_googleapis_com.api.request_count
      type: count,delta
      name: Requests
      unit: "1"
      gcpOptions:
        ingestDelay: 240s
        samplePeriod: 60s
        valueType: INT64
        metricKind: DELTA
      dimensions:
        - value: metric.labels.response_code
        - value: metric.labels.api_method
    - value: datastore.googleapis.com/entity/read_sizes
      id: cloud.gcp.datastore_googleapis_com.entity.read_sizes
      type: gauge
      name: Sizes of read entities
      unit: By
      gcpOptions:
        ingestDelay: 240s
        samplePeriod: 60s
        valueType: DISTRIBUTION
        metricKind: DELTA
      dimensions:
        - value: metric.labels.type
dashboards:
  - dashboard: "dashboards/datastore.json"