id: filestore_instance
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
- id: filter_conditions
  displayName: Metric query filter for which metrics should be queried
  type: variables
technology:
  name: Google Filestore Instance
gcp:
- service: filestore_instance
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: label:resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: label:resource.labels.project_id
    key: gcp.project.id
  - value: label:resource.labels.location
    key: location
    compatibilityModeOnly: true
  - value: label:resource.labels.location
    key: gcp.region
  - value: label:resource.labels.instance_name
    key: instance_name
    compatibilityModeOnly: true
  - value: label:resource.labels.instance_name
    key: gcp.instance.name
  metrics:
  - value: metric:file.googleapis.com/nfs/server/average_read_latency
    key: cloud.gcp.file_googleapis_com.nfs.server.average_read_latency
    type: gauge
    name: Average read latency
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: ms
    dimensions:
    - value: label:metric.labels.file_share
      key: file_share
  - value: metric:file.googleapis.com/nfs/server/average_write_latency
    key: cloud.gcp.file_googleapis_com.nfs.server.average_write_latency
    type: gauge
    name: Average write latency
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: ms
    dimensions:
    - value: label:metric.labels.file_share
      key: file_share
  - value: metric:file.googleapis.com/nfs/server/free_bytes
    key: cloud.gcp.file_googleapis_com.nfs.server.free_bytes
    type: gauge
    name: Free disk bytes
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: By
    dimensions:
    - value: label:metric.labels.file_share
      key: file_share
  - value: metric:file.googleapis.com/nfs/server/free_bytes_percent
    key: cloud.gcp.file_googleapis_com.nfs.server.free_bytes_percent
    type: gauge
    name: Free disk space percent
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: '%'
    dimensions:
    - value: label:metric.labels.file_share
      key: file_share
  - value: metric:file.googleapis.com/nfs/server/metadata_ops_count
    key: cloud.gcp.file_googleapis_com.nfs.server.metadata_ops_count
    type: count,delta
    name: Metadata operation count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.file_share
      key: file_share
  - value: metric:file.googleapis.com/nfs/server/procedure_call_count
    key: cloud.gcp.file_googleapis_com.nfs.server.procedure_call_count
    type: count,delta
    name: Procedure call count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.name
      key: name
    - value: label:metric.labels.version
      key: version
  - value: metric:file.googleapis.com/nfs/server/read_bytes_count
    key: cloud.gcp.file_googleapis_com.nfs.server.read_bytes_count
    type: count,delta
    name: Bytes read
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: label:metric.labels.file_share
      key: file_share
  - value: metric:file.googleapis.com/nfs/server/read_milliseconds_count
    key: cloud.gcp.file_googleapis_com.nfs.server.read_milliseconds_count
    type: count,delta
    name: Time (in milliseconds) spent on read operations
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: ms
    dimensions:
    - value: label:metric.labels.file_share
      key: file_share
  - value: metric:file.googleapis.com/nfs/server/read_ops_count
    key: cloud.gcp.file_googleapis_com.nfs.server.read_ops_count
    type: count,delta
    name: Disk read operation count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.file_share
      key: file_share
  - value: metric:file.googleapis.com/nfs/server/used_bytes
    key: cloud.gcp.file_googleapis_com.nfs.server.used_bytes
    type: gauge
    name: Used disk bytes
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: By
    dimensions:
    - value: label:metric.labels.file_share
      key: file_share
  - value: metric:file.googleapis.com/nfs/server/used_bytes_percent
    key: cloud.gcp.file_googleapis_com.nfs.server.used_bytes_percent
    type: gauge
    name: Used disk space percent
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: '%'
    dimensions:
    - value: label:metric.labels.file_share
      key: file_share
  - value: metric:file.googleapis.com/nfs/server/write_bytes_count
    key: cloud.gcp.file_googleapis_com.nfs.server.write_bytes_count
    type: count,delta
    name: Bytes written
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: label:metric.labels.file_share
      key: file_share
  - value: metric:file.googleapis.com/nfs/server/write_milliseconds_count
    key: cloud.gcp.file_googleapis_com.nfs.server.write_milliseconds_count
    type: count,delta
    name: Time (in milliseconds) spent on write operations
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: ms
    dimensions:
    - value: label:metric.labels.file_share
      key: file_share
  - value: metric:file.googleapis.com/nfs/server/write_ops_count
    key: cloud.gcp.file_googleapis_com.nfs.server.write_ops_count
    type: count,delta
    name: Disk write operation count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.file_share
      key: file_share
dashboards:
- dashboard: dashboards/filestore_instance.json
