id: gae_app
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
- id: filter_conditions
  displayName: Metric query filter for which metrics should be queried
  type: variables
technology:
  name: Google App Engine Application
gcp:
- service: gae_app
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: label:resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: label:resource.labels.project_id
    key: gcp.project.id
  - value: label:resource.labels.module_id
    key: module_id
  - value: label:resource.labels.version_id
    key: version_id
  - value: label:resource.labels.zone
    key: zone
    compatibilityModeOnly: true
  - value: label:resource.labels.zone
    key: gcp.region
  metrics:
  - value: metric:agent.googleapis.com/agent/api_request_count
    key: cloud.gcp.agent_googleapis_com.agent.api_request_count
    type: count,delta
    name: Monitoring Agent API Request Count
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: INT64
      metricKind: CUMULATIVE
      unit: '1'
    dimensions:
    - value: label:metric.labels.state
      key: state
  - value: metric:agent.googleapis.com/agent/log_entry_count
    key: cloud.gcp.agent_googleapis_com.agent.log_entry_count
    type: count,delta
    name: Logging Agent Log Entry Count
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: INT64
      metricKind: CUMULATIVE
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:agent.googleapis.com/agent/log_entry_retry_count
    key: cloud.gcp.agent_googleapis_com.agent.log_entry_retry_count
    type: count,delta
    name: Logging Agent Retried Log Entry Writes Count
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: INT64
      metricKind: CUMULATIVE
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:agent.googleapis.com/agent/memory_usage
    key: cloud.gcp.agent_googleapis_com.agent.memory_usage
    type: gauge
    name: Monitoring Agent Memory Usage
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: By
    dimensions: []
  - value: metric:agent.googleapis.com/agent/monitoring/point_count
    key: cloud.gcp.agent_googleapis_com.agent.monitoring.point_count
    type: count,delta
    name: Monitoring Agent Metric Point Count
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: INT64
      metricKind: CUMULATIVE
      unit: '1'
    dimensions:
    - value: label:metric.labels.status
      key: status
  - value: metric:agent.googleapis.com/agent/request_count
    key: cloud.gcp.agent_googleapis_com.agent.request_count
    type: count,delta
    name: Logging Agent API Request Count
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: INT64
      metricKind: CUMULATIVE
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:agent.googleapis.com/agent/streamspace_size
    key: cloud.gcp.agent_googleapis_com.agent.streamspace_size
    type: gauge
    name: Monitoring Agent Process Labels Size
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: By
    dimensions: []
  - value: metric:agent.googleapis.com/agent/streamspace_size_throttling
    key: cloud.gcp.agent_googleapis_com.agent.streamspace_size_throttling
    type: gauge
    name: Monitoring Agent is Throttling Processes
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: metric:agent.googleapis.com/agent/uptime
    key: cloud.gcp.agent_googleapis_com.agent.uptime
    type: count,delta
    name: Monitoring/Logging Agent Uptime
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: INT64
      metricKind: CUMULATIVE
      unit: s
    dimensions:
    - value: label:metric.labels.version
      key: version
  - value: metric:appengine.googleapis.com/flex/autoscaler/capacity
    key: cloud.gcp.appengine_googleapis_com.flex.autoscaler.capacity
    type: gauge
    name: Autoscaling Metrics Utilization Capacity
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: metric:appengine.googleapis.com/flex/autoscaler/current_utilization
    key: cloud.gcp.appengine_googleapis_com.flex.autoscaler.current_utilization
    type: gauge
    name: Autoscaling Metrics Current Utilization
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.metric_type
      key: metric_type
  - value: metric:appengine.googleapis.com/flex/connections/current
    key: cloud.gcp.appengine_googleapis_com.flex.connections.current
    type: gauge
    name: Connections
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: metric:appengine.googleapis.com/flex/cpu/reserved_cores
    key: cloud.gcp.appengine_googleapis_com.flex.cpu.reserved_cores
    type: gauge
    name: Reserved cores
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: metric:appengine.googleapis.com/flex/cpu/utilization
    key: cloud.gcp.appengine_googleapis_com.flex.cpu.utilization
    type: gauge
    name: CPU utilization
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: 10^2.%
    dimensions: []
  - value: metric:appengine.googleapis.com/flex/disk/read_bytes_count
    key: cloud.gcp.appengine_googleapis_com.flex.disk.read_bytes_count
    type: count,delta
    name: Disk bytes read
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions: []
  - value: metric:appengine.googleapis.com/flex/disk/write_bytes_count
    key: cloud.gcp.appengine_googleapis_com.flex.disk.write_bytes_count
    type: count,delta
    name: Disk bytes written
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions: []
  - value: metric:appengine.googleapis.com/flex/network/received_bytes_count
    key: cloud.gcp.appengine_googleapis_com.flex.network.received_bytes_count
    type: count,delta
    name: Network bytes received.
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions: []
  - value: metric:appengine.googleapis.com/flex/network/sent_bytes_count
    key: cloud.gcp.appengine_googleapis_com.flex.network.sent_bytes_count
    type: count,delta
    name: Network bytes sent.
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions: []
  - value: metric:appengine.googleapis.com/http/server/dos_intercept_count
    key: cloud.gcp.appengine_googleapis_com.http.server.dos_intercept_count
    type: count,delta
    name: Interception count
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions: []
  - value: metric:appengine.googleapis.com/http/server/quota_denial_count
    key: cloud.gcp.appengine_googleapis_com.http.server.quota_denial_count
    type: count,delta
    name: Quota denial count
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions: []
  - value: metric:appengine.googleapis.com/http/server/response_count
    key: cloud.gcp.appengine_googleapis_com.http.server.response_count
    type: count,delta
    name: Response count
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.loading
      key: loading
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:appengine.googleapis.com/http/server/response_latencies
    key: cloud.gcp.appengine_googleapis_com.http.server.response_latencies
    type: gauge
    name: Response latency
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: ms
    dimensions:
    - value: label:metric.labels.loading
      key: loading
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:appengine.googleapis.com/http/server/response_style_count
    key: cloud.gcp.appengine_googleapis_com.http.server.response_style_count
    type: count,delta
    name: Response count by style
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.dynamic
      key: dynamic
    - value: label:metric.labels.cached
      key: cached
  - value: metric:appengine.googleapis.com/memcache/centi_mcu_count
    key: cloud.gcp.appengine_googleapis_com.memcache.centi_mcu_count
    type: count,delta
    name: Memcache utilization
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.command
      key: command
  - value: metric:appengine.googleapis.com/memcache/hit_ratio
    key: cloud.gcp.appengine_googleapis_com.memcache.hit_ratio
    type: gauge
    name: Hit ratio
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: metric:appengine.googleapis.com/memcache/operation_count
    key: cloud.gcp.appengine_googleapis_com.memcache.operation_count
    type: count,delta
    name: Memcache operations
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.command
      key: command
    - value: label:metric.labels.status
      key: status
  - value: metric:appengine.googleapis.com/memcache/received_bytes_count
    key: cloud.gcp.appengine_googleapis_com.memcache.received_bytes_count
    type: count,delta
    name: Memcache received bytes
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: label:metric.labels.status
      key: status
    - value: label:metric.labels.command
      key: command
  - value: metric:appengine.googleapis.com/memcache/sent_bytes_count
    key: cloud.gcp.appengine_googleapis_com.memcache.sent_bytes_count
    type: count,delta
    name: Memcache sent bytes
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: label:metric.labels.command
      key: command
  - value: metric:appengine.googleapis.com/memcache/used_cache_size
    key: cloud.gcp.appengine_googleapis_com.memcache.used_cache_size
    type: gauge
    name: Used Cache Size
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: By
    dimensions: []
  - value: metric:appengine.googleapis.com/system/billed_instance_estimate_count
    key: cloud.gcp.appengine_googleapis_com.system.billed_instance_estimate_count
    type: gauge
    name: Estimated instance count
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: metric:appengine.googleapis.com/system/cpu/usage
    key: cloud.gcp.appengine_googleapis_com.system.cpu.usage
    type: gauge
    name: CPU megacycles
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.source
      key: source
  - value: metric:appengine.googleapis.com/system/instance_count
    key: cloud.gcp.appengine_googleapis_com.system.instance_count
    type: gauge
    name: Instance count
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.state
      key: state
  - value: metric:appengine.googleapis.com/system/memory/usage
    key: cloud.gcp.appengine_googleapis_com.system.memory.usage
    type: gauge
    name: Memory usage
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: By
    dimensions: []
  - value: metric:appengine.googleapis.com/system/network/received_bytes_count
    key: cloud.gcp.appengine_googleapis_com.system.network.received_bytes_count
    type: count,delta
    name: Received bytes
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: label:metric.labels.cached
      key: cached
  - value: metric:appengine.googleapis.com/system/network/sent_bytes_count
    key: cloud.gcp.appengine_googleapis_com.system.network.sent_bytes_count
    type: count,delta
    name: Sent bytes
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: label:metric.labels.cached
      key: cached
alerts:
- path: alerts/gae_app/cpu.utilization.json
