id: gce_zone_network_health
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
- id: filter_conditions
  displayName: Metric query filter for which metrics should be queried
  type: variables
technology:
  name: Google Zone Network Health
gcp:
- service: gce_zone_network_health
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: label:resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: label:resource.labels.project_id
    key: gcp.project.id
  - value: label:resource.labels.zone
    key: zone
    compatibilityModeOnly: true
  - value: label:resource.labels.zone
    key: gcp.region
  - value: label:resource.labels.region
    key: region
  metrics:
  - value: metric:networking.googleapis.com/cloud_netslo/active_probing/probe_count
    key: cloud.gcp.networking_googleapis_com.cloud_netslo.active_probing.probe_count
    type: count,delta
    name: Number of probes
    gcpOptions:
      ingestDelay: 420
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.remote_zone
      key: remote_zone
    - value: label:metric.labels.remote_region
      key: remote_region
    - value: label:metric.labels.remote_location_type
      key: remote_location_type
    - value: label:metric.labels.protocol
      key: protocol
    - value: label:metric.labels.result
      key: result
