id: gce_instance
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
- id: filter_conditions
  displayName: Metric query filter for which metrics should be queried
  type: variables
technology:
  name: Google VM Instance Uptime Checks
gcp:
- service: gce_instance
  featureSet: uptime_check
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: label:resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: label:resource.labels.project_id
    key: gcp.project.id
  - value: label:resource.labels.instance_id
    key: instance_id
    compatibilityModeOnly: true
  - value: label:resource.labels.instance_id
    key: gcp.instance.id
  - value: label:resource.labels.zone
    key: zone
    compatibilityModeOnly: true
  - value: label:resource.labels.zone
    key: gcp.region
  metrics:
  - value: metric:monitoring.googleapis.com/uptime_check/content_mismatch
    key: cloud.gcp.monitoring_googleapis_com.uptime_check.content_mismatch
    type: gauge
    name: Content mismatch
    gcpOptions:
      ingestDelay: 35
      samplePeriod: 60
      valueType: BOOL
      metricKind: GAUGE
      unit: ''
    dimensions:
    - value: label:metric.labels.check_id
      key: check_id
    - value: label:metric.labels.checker_location
      key: checker_location
    - value: label:metric.labels.checker_project_id
      key: checker_project_id
    - value: label:metric.labels.checker_network
      key: checker_network
    - value: label:metric.labels.checker_zone
      key: checker_zone
    - value: label:metric.labels.checked_resource_id
      key: checked_resource_id
  - value: metric:monitoring.googleapis.com/uptime_check/error_code
    key: cloud.gcp.monitoring_googleapis_com.uptime_check.error_code
    type: gauge
    name: Error code
    gcpOptions:
      ingestDelay: 35
      samplePeriod: 60
      valueType: STRING
      metricKind: GAUGE
      unit: ''
    dimensions:
    - value: label:metric.labels.check_id
      key: check_id
    - value: label:metric.labels.checker_location
      key: checker_location
    - value: label:metric.labels.checker_project_id
      key: checker_project_id
    - value: label:metric.labels.checker_network
      key: checker_network
    - value: label:metric.labels.checker_zone
      key: checker_zone
    - value: label:metric.labels.checked_resource_id
      key: checked_resource_id
  - value: metric:monitoring.googleapis.com/uptime_check/http_status
    key: cloud.gcp.monitoring_googleapis_com.uptime_check.http_status
    type: gauge
    name: HTTP status
    gcpOptions:
      ingestDelay: 35
      samplePeriod: 60
      valueType: STRING
      metricKind: GAUGE
      unit: ''
    dimensions:
    - value: label:metric.labels.check_id
      key: check_id
    - value: label:metric.labels.checker_location
      key: checker_location
    - value: label:metric.labels.checker_project_id
      key: checker_project_id
    - value: label:metric.labels.checker_network
      key: checker_network
    - value: label:metric.labels.checker_zone
      key: checker_zone
    - value: label:metric.labels.checked_resource_id
      key: checked_resource_id
  - value: metric:monitoring.googleapis.com/uptime_check/request_latency
    key: cloud.gcp.monitoring_googleapis_com.uptime_check.request_latency
    type: gauge
    name: Request latency
    gcpOptions:
      ingestDelay: 35
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: ms
    dimensions:
    - value: label:metric.labels.check_id
      key: check_id
    - value: label:metric.labels.checker_location
      key: checker_location
    - value: label:metric.labels.checker_project_id
      key: checker_project_id
    - value: label:metric.labels.checker_network
      key: checker_network
    - value: label:metric.labels.checker_zone
      key: checker_zone
    - value: label:metric.labels.checked_resource_id
      key: checked_resource_id
  - value: metric:monitoring.googleapis.com/uptime_check/time_until_ssl_cert_expires
    key: cloud.gcp.monitoring_googleapis_com.uptime_check.time_until_ssl_cert_expires
    type: gauge
    name: Time until SSL certificate expires
    gcpOptions:
      ingestDelay: 35
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: d
    dimensions:
    - value: label:metric.labels.check_id
      key: check_id
    - value: label:metric.labels.checker_location
      key: checker_location
    - value: label:metric.labels.checker_project_id
      key: checker_project_id
    - value: label:metric.labels.checker_network
      key: checker_network
    - value: label:metric.labels.checker_zone
      key: checker_zone
    - value: label:metric.labels.checked_resource_id
      key: checked_resource_id
