id: gce_instance_vm_flow
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google VM Instance VM Flow
gcp:
- service: gce_instance_vm_flow
  featureSet: default
  dimensions:
  - value: resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    key: gcp.project.id
  - value: resource.labels.instance_id
    key: instance_id
    compatibilityModeOnly: true
  - value: resource.labels.instance_id
    key: gcp.instance.id
  - value: resource.labels.zone
    key: zone
    compatibilityModeOnly: true
  - value: resource.labels.zone
    key: gcp.region
  metrics:
  - value: networking.googleapis.com/vm_flow/egress_bytes_count
    key: cloud.gcp.networking_googleapis_com.vm_flow.egress_bytes_count
    type: count,delta
    name: Egress bytes
    gcpOptions:
      ingestDelay: 150
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: metric.labels.local_network
    - value: metric.labels.local_subnetwork
    - value: metric.labels.local_network_interface
    - value: metric.labels.remote_country
    - value: metric.labels.remote_continent
    - value: metric.labels.remote_zone
    - value: metric.labels.remote_location_type
    - value: metric.labels.remote_network
    - value: metric.labels.remote_subnetwork
    - value: metric.labels.protocol
    - value: metric.labels.network_topology_remote_label
    - value: metric.labels.remote_vpn_tunnel
  - value: networking.googleapis.com/vm_flow/ingress_bytes_count
    key: cloud.gcp.networking_googleapis_com.vm_flow.ingress_bytes_count
    type: count,delta
    name: Ingress bytes
    gcpOptions:
      ingestDelay: 150
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: metric.labels.local_network
    - value: metric.labels.local_subnetwork
    - value: metric.labels.local_network_interface
    - value: metric.labels.remote_country
    - value: metric.labels.remote_continent
    - value: metric.labels.remote_zone
    - value: metric.labels.remote_location_type
    - value: metric.labels.remote_network
    - value: metric.labels.remote_subnetwork
    - value: metric.labels.protocol
    - value: metric.labels.network_topology_remote_label
    - value: metric.labels.remote_vpn_tunnel
  - value: networking.googleapis.com/vm_flow/rtt
    key: cloud.gcp.networking_googleapis_com.vm_flow.rtt
    type: gauge
    name: RTT latencies
    gcpOptions:
      ingestDelay: 150
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: ms
    dimensions:
    - value: metric.labels.local_network
    - value: metric.labels.local_subnetwork
    - value: metric.labels.local_network_interface
    - value: metric.labels.remote_country
    - value: metric.labels.remote_continent
    - value: metric.labels.remote_zone
    - value: metric.labels.remote_location_type
    - value: metric.labels.remote_network
    - value: metric.labels.remote_subnetwork
    - value: metric.labels.protocol
    - value: metric.labels.network_topology_remote_label
    - value: metric.labels.remote_vpn_tunnel
