id: gcs_bucket
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud Storage bucket
gcp:
- service: gcs_bucket
  featureSet: default
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    key: gcp.project.id
  - value: resource.labels.bucket_name
    key: bucket_name
    compatibilityModeOnly: true
  - value: resource.labels.bucket_name
    key: gcp.instance.name
  - value: resource.labels.location
    key: location
    compatibilityModeOnly: true
  - value: resource.labels.location
    key: gcp.region
  metrics:
  - value: firebasestorage.googleapis.com/rules/evaluation_count
    key: cloud.gcp.firebasestorage_googleapis_com.rules.evaluation_count
    type: count,delta
    name: Rule evaluations
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.request_method
    - value: metric.labels.ruleset_label
    - value: metric.labels.result
  - value: storage.googleapis.com/api/request_count
    key: cloud.gcp.storage_googleapis_com.api.request_count
    type: count,delta
    name: Request count
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.response_code
    - value: metric.labels.method
  - value: storage.googleapis.com/authn/authentication_count
    key: cloud.gcp.storage_googleapis_com.authn.authentication_count
    type: count,delta
    name: Authentication count
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.authentication_method
    - value: metric.labels.response_code
    - value: metric.labels.method
    - value: metric.labels.access_id
  - value: storage.googleapis.com/authz/acl_based_object_access_count
    key: cloud.gcp.storage_googleapis_com.authz.acl_based_object_access_count
    type: count,delta
    name: Object-ACL based access count
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions: []
  - value: storage.googleapis.com/authz/acl_operations_count
    key: cloud.gcp.storage_googleapis_com.authz.acl_operations_count
    type: count,delta
    name: ACLs usage
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.acl_operation
  - value: storage.googleapis.com/authz/object_specific_acl_mutation_count
    key: cloud.gcp.storage_googleapis_com.authz.object_specific_acl_mutation_count
    type: count,delta
    name: Object ACL changes
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions: []
  - value: storage.googleapis.com/network/received_bytes_count
    key: cloud.gcp.storage_googleapis_com.network.received_bytes_count
    type: count,delta
    name: Received bytes
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: metric.labels.response_code
    - value: metric.labels.method
  - value: storage.googleapis.com/network/sent_bytes_count
    key: cloud.gcp.storage_googleapis_com.network.sent_bytes_count
    type: count,delta
    name: Sent bytes
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: metric.labels.response_code
    - value: metric.labels.method
  - value: storage.googleapis.com/storage/object_count
    key: cloud.gcp.storage_googleapis_com.storage.object_count
    type: gauge
    name: Object count
    gcpOptions:
      ingestDelay: 600
      samplePeriod: 300
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: metric.labels.storage_class
  - value: storage.googleapis.com/storage/total_byte_seconds
    key: cloud.gcp.storage_googleapis_com.storage.total_byte_seconds
    type: gauge
    name: Total byte seconds
    gcpOptions:
      ingestDelay: 600
      samplePeriod: 300
      valueType: DOUBLE
      metricKind: GAUGE
      unit: By.s
    dimensions:
    - value: metric.labels.storage_class
  - value: storage.googleapis.com/storage/total_bytes
    key: cloud.gcp.storage_googleapis_com.storage.total_bytes
    type: gauge
    name: Total bytes
    gcpOptions:
      ingestDelay: 600
      samplePeriod: 300
      valueType: DOUBLE
      metricKind: GAUGE
      unit: By
    dimensions:
    - value: metric.labels.storage_class
dashboards:
  - dashboard: "dashboards/gcs_bucket.json"