id: https_lb_rule
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud HTTP/S Load Balancing Rule
gcp:
- service: https_lb_rule
  featureSet: default
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    key: gcp.project.id
  - value: resource.labels.region
    key: region
    compatibilityModeOnly: true
  - value: resource.labels.region
    key: gcp.region
  - value: resource.labels.url_map_name
    key: url_map_name
    compatibilityModeOnly: true
  - value: resource.labels.url_map_name
    key: gcp.instance.name
  - value: resource.labels.forwarding_rule_name
    key: forwarding_rule_name
  - value: resource.labels.target_proxy_name
    key: target_proxy_name
  - value: resource.labels.matched_url_path_rule
    key: matched_url_path_rule
  - value: resource.labels.backend_target_name
    key: backend_target_name
  - value: resource.labels.backend_target_type
    key: backend_target_type
  - value: resource.labels.backend_name
    key: backend_name
  - value: resource.labels.backend_type
    key: backend_type
  - value: resource.labels.backend_scope
    key: backend_scope
  - value: resource.labels.backend_scope_type
    key: backend_scope_type
  metrics:
  - value: loadbalancing.googleapis.com/https/backend_latencies
    key: cloud.gcp.loadbalancing_googleapis_com.https.backend_latencies
    type: gauge
    name: Backend latency
    gcpOptions:
      ingestDelay: 210
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: ms
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.proxy_continent
    - value: metric.labels.cache_result
    - value: metric.labels.client_country
  - value: loadbalancing.googleapis.com/https/backend_request_bytes_count
    key: cloud.gcp.loadbalancing_googleapis_com.https.backend_request_bytes_count
    type: count,delta
    name: Backend Request Bytes
    gcpOptions:
      ingestDelay: 210
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.proxy_continent
    - value: metric.labels.cache_result
  - value: loadbalancing.googleapis.com/https/backend_request_count
    key: cloud.gcp.loadbalancing_googleapis_com.https.backend_request_count
    type: count,delta
    name: Backend Request Count
    gcpOptions:
      ingestDelay: 210
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.proxy_continent
    - value: metric.labels.cache_result
  - value: loadbalancing.googleapis.com/https/backend_response_bytes_count
    key: cloud.gcp.loadbalancing_googleapis_com.https.backend_response_bytes_count
    type: count,delta
    name: Backend Response Bytes
    gcpOptions:
      ingestDelay: 210
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.proxy_continent
    - value: metric.labels.cache_result
  - value: loadbalancing.googleapis.com/https/frontend_tcp_rtt
    key: cloud.gcp.loadbalancing_googleapis_com.https.frontend_tcp_rtt
    type: gauge
    name: Frontend RTT
    gcpOptions:
      ingestDelay: 210
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: ms
    dimensions:
    - value: metric.labels.proxy_continent
    - value: metric.labels.client_country
  - value: loadbalancing.googleapis.com/https/request_bytes_count
    key: cloud.gcp.loadbalancing_googleapis_com.https.request_bytes_count
    type: count,delta
    name: Request bytes
    gcpOptions:
      ingestDelay: 210
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.proxy_continent
    - value: metric.labels.cache_result
    - value: metric.labels.client_country
  - value: loadbalancing.googleapis.com/https/request_count
    key: cloud.gcp.loadbalancing_googleapis_com.https.request_count
    type: count,delta
    name: Request count
    gcpOptions:
      ingestDelay: 210
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.proxy_continent
    - value: metric.labels.cache_result
    - value: metric.labels.client_country
  - value: loadbalancing.googleapis.com/https/response_bytes_count
    key: cloud.gcp.loadbalancing_googleapis_com.https.response_bytes_count
    type: count,delta
    name: Response bytes
    gcpOptions:
      ingestDelay: 210
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.proxy_continent
    - value: metric.labels.cache_result
    - value: metric.labels.client_country
  - value: loadbalancing.googleapis.com/https/total_latencies
    key: cloud.gcp.loadbalancing_googleapis_com.https.total_latencies
    type: gauge
    name: Total latency
    gcpOptions:
      ingestDelay: 210
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: ms
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.proxy_continent
    - value: metric.labels.cache_result
    - value: metric.labels.client_country
