id: https_lb_rule
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud HTTP/S Load Balancing Rule
gcp:
- service: https_lb_rule
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.region
    id: region
    compatibilityModeOnly: true
  - value: resource.labels.region
    id: gcp.region
  - value: resource.labels.url_map_name
    id: url_map_name
    compatibilityModeOnly: true
  - value: resource.labels.url_map_name
    id: gcp.instance.name
  - value: resource.labels.forwarding_rule_name
    id: forwarding_rule_name
  - value: resource.labels.target_proxy_name
    id: target_proxy_name
  - value: resource.labels.matched_url_path_rule
    id: matched_url_path_rule
  - value: resource.labels.backend_target_name
    id: backend_target_name
  - value: resource.labels.backend_target_type
    id: backend_target_type
  - value: resource.labels.backend_name
    id: backend_name
  - value: resource.labels.backend_type
    id: backend_type
  - value: resource.labels.backend_scope
    id: backend_scope
  - value: resource.labels.backend_scope_type
    id: backend_scope_type
  metrics:
  - value: loadbalancing.googleapis.com/https/backend_latencies
    id: cloud.gcp.loadbalancing_googleapis_com.https.backend_latencies
    type: gauge
    name: Backend latency
    unit: ms
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.proxy_continent
    - value: metric.labels.cache_result
    - value: metric.labels.client_country
  - value: loadbalancing.googleapis.com/https/backend_request_bytes_count
    id: cloud.gcp.loadbalancing_googleapis_com.https.backend_request_bytes_count
    type: count,delta
    name: Backend Request Bytes
    unit: By
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.proxy_continent
    - value: metric.labels.cache_result
  - value: loadbalancing.googleapis.com/https/backend_request_count
    id: cloud.gcp.loadbalancing_googleapis_com.https.backend_request_count
    type: count,delta
    name: Backend Request Count
    unit: '1'
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.proxy_continent
    - value: metric.labels.cache_result
  - value: loadbalancing.googleapis.com/https/backend_response_bytes_count
    id: cloud.gcp.loadbalancing_googleapis_com.https.backend_response_bytes_count
    type: count,delta
    name: Backend Response Bytes
    unit: By
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.proxy_continent
    - value: metric.labels.cache_result
  - value: loadbalancing.googleapis.com/https/frontend_tcp_rtt
    id: cloud.gcp.loadbalancing_googleapis_com.https.frontend_tcp_rtt
    type: gauge
    name: Frontend RTT
    unit: ms
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.proxy_continent
    - value: metric.labels.client_country
  - value: loadbalancing.googleapis.com/https/request_bytes_count
    id: cloud.gcp.loadbalancing_googleapis_com.https.request_bytes_count
    type: count,delta
    name: Request bytes
    unit: By
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.proxy_continent
    - value: metric.labels.cache_result
    - value: metric.labels.client_country
  - value: loadbalancing.googleapis.com/https/request_count
    id: cloud.gcp.loadbalancing_googleapis_com.https.request_count
    type: count,delta
    name: Request count
    unit: '1'
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.proxy_continent
    - value: metric.labels.cache_result
    - value: metric.labels.client_country
  - value: loadbalancing.googleapis.com/https/response_bytes_count
    id: cloud.gcp.loadbalancing_googleapis_com.https.response_bytes_count
    type: count,delta
    name: Response bytes
    unit: By
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.proxy_continent
    - value: metric.labels.cache_result
    - value: metric.labels.client_country
  - value: loadbalancing.googleapis.com/https/total_latencies
    id: cloud.gcp.loadbalancing_googleapis_com.https.total_latencies
    type: gauge
    name: Total latency
    unit: ms
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.proxy_continent
    - value: metric.labels.cache_result
    - value: metric.labels.client_country
