id: k8s_cluster
version: 0.0.1
minDynatraceVersion: 1.199
vars:
- id: filter_conditions
  displayName: Metric query filter for which metrics should be queried
  type: variables
technology:
  name: Google Kubernetes Cluster
gcp:
- service: k8s_cluster
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: label:resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: label:resource.labels.project_id
    key: gcp.project.id
  - value: label:resource.labels.location
    key: location
    compatibilityModeOnly: true
  - value: label:resource.labels.location
    key: gcp.region
  - value: label:resource.labels.cluster_name
    key: cluster_name
    compatibilityModeOnly: false
  - value: label:resource.labels.cluster_name
    key: gcp.instance.name
  metrics:
  - value: metric:logging.googleapis.com/log_entry_count
    key: cloud.gcp.logging.googleapis.com.log_entry_count
    type: gauge
    name: Log entries
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.log
      key: log
    - value: label:metric.labels.severity
      key: severity
