id: k8s_cluster
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google Kubernetes Cluster
gcp:
- service: k8s_cluster
  featureSet: default
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.location
    id: location
  - value: resource.labels.cluster_name
    id: cluster_name
  metrics:
  - value: logging.googleapis.com/log_entry_count
    id: cloud.gcp.logging.googleapis.com.log_entry_count
    type: gauge
    name: Log entries
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.log
    - value: metric.labels.severity