id: k8s_cluster
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Kubernetes Cluster
gcp:
- service: k8s_cluster
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.location
    id: location
    compatibilityModeOnly: true
  - value: resource.labels.location
    id: gcp.region
  - value: resource.labels.cluster_name
    id: cluster_name
    compatibilityModeOnly: false
  - value: resource.labels.cluster_name
    id: gcp.instance.name
  metrics:
  - value: logging.googleapis.com/log_entry_count
    id: cloud.gcp.logging.googleapis.com.log_entry_count
    type: gauge
    name: Log entries
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.log
    - value: metric.labels.severity