id: k8s_container
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Kubernetes Container Agent
gcp:
- service: k8s_container
  featureSet: agent
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    key: gcp.project.id
  - value: resource.labels.location
    key: location
    compatibilityModeOnly: true
  - value: resource.labels.location
    key: gcp.region
  - value: resource.labels.cluster_name
    key: cluster_name
  - value: resource.labels.namespace_name
    key: namespace_name
  - value: resource.labels.pod_name
    key: pod_name
  - value: resource.labels.container_name
    key: container_name
    compatibilityModeOnly: false
  - value: resource.labels.container_name
    key: gcp.instance.name
  metrics:
  - value: agent.googleapis.com/agent/api_request_count
    key: cloud.gcp.agent_googleapis_com.agent.api_request_count
    type: count,delta
    name: Monitoring Agent API Request Count
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: INT64
      metricKind: CUMULATIVE
      unit: '1'
    dimensions:
    - value: metric.labels.state
  - value: agent.googleapis.com/agent/log_entry_count
    key: cloud.gcp.agent_googleapis_com.agent.log_entry_count
    type: count,delta
    name: Logging Agent Log Entry Count
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: INT64
      metricKind: CUMULATIVE
      unit: '1'
    dimensions:
    - value: metric.labels.response_code
  - value: agent.googleapis.com/agent/log_entry_retry_count
    key: cloud.gcp.agent_googleapis_com.agent.log_entry_retry_count
    type: count,delta
    name: Logging Agent Retried Log Entry Writes Count
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: INT64
      metricKind: CUMULATIVE
      unit: '1'
    dimensions:
    - value: metric.labels.response_code
  - value: agent.googleapis.com/agent/memory_usage
    key: cloud.gcp.agent_googleapis_com.agent.memory_usage
    type: gauge
    name: Monitoring Agent Memory Usage
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: By
    dimensions: []
  - value: agent.googleapis.com/agent/monitoring/point_count
    key: cloud.gcp.agent_googleapis_com.agent.monitoring.point_count
    type: count,delta
    name: Monitoring Agent Metric Point Count
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: INT64
      metricKind: CUMULATIVE
      unit: '1'
    dimensions:
    - value: metric.labels.status
  - value: agent.googleapis.com/agent/request_count
    key: cloud.gcp.agent_googleapis_com.agent.request_count
    type: count,delta
    name: Logging Agent API Request Count
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: INT64
      metricKind: CUMULATIVE
      unit: '1'
    dimensions:
    - value: metric.labels.response_code
  - value: agent.googleapis.com/agent/streamspace_size
    key: cloud.gcp.agent_googleapis_com.agent.streamspace_size
    type: gauge
    name: Monitoring Agent Process Labels Size
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: By
    dimensions: []
  - value: agent.googleapis.com/agent/streamspace_size_throttling
    key: cloud.gcp.agent_googleapis_com.agent.streamspace_size_throttling
    type: gauge
    name: Monitoring Agent is Throttling Processes
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: agent.googleapis.com/agent/uptime
    key: cloud.gcp.agent_googleapis_com.agent.uptime
    type: count,delta
    name: Monitoring/Logging Agent Uptime
    gcpOptions:
      ingestDelay: 0
      samplePeriod: 60
      valueType: INT64
      metricKind: CUMULATIVE
      unit: s
    dimensions:
    - value: metric.labels.version