id: k8s_pod
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Kubernetes Pod
gcp:
- service: k8s_pod
  featureSet: istio
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    key: gcp.project.id
  - value: resource.labels.location
    key: location
    compatibilityModeOnly: true
  - value: resource.labels.location
    key: gcp.region
  - value: resource.labels.cluster_name
    key: cluster_name
  - value: resource.labels.namespace_name
    key: namespace_name
  - value: resource.labels.pod_name
    key: pod_name
    compatibilityModeOnly: false
  - value: resource.labels.pod_name
    key: gcp.instance.name
  metrics:
  - value: istio.io/service/client/connection_close_count
    key: cloud.gcp.istio_io.service.client.connection_close_count
    type: count,delta
    name: Client Connection Close Count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: CUMULATIVE
      unit: By
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
  - value: istio.io/service/client/connection_open_count
    key: cloud.gcp.istio_io.service.client.connection_open_count
    type: count,delta
    name: Client Connection Open Count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: CUMULATIVE
      unit: By
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
  - value: istio.io/service/client/received_bytes_count
    key: cloud.gcp.istio_io.service.client.received_bytes_count
    type: count,delta
    name: Client Received Bytes Count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: CUMULATIVE
      unit: By
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
  - value: istio.io/service/client/request_bytes
    key: cloud.gcp.istio_io.service.client.request_bytes
    type: gauge
    name: Client Request Bytes
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: By
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
    - value: metric.labels.request_operation
    - value: metric.labels.api_version
    - value: metric.labels.response_code
    - value: metric.labels.api_name
  - value: istio.io/service/client/request_count
    key: cloud.gcp.istio_io.service.client.request_count
    type: count,delta
    name: Client Request Count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
    - value: metric.labels.request_operation
    - value: metric.labels.api_version
    - value: metric.labels.response_code
    - value: metric.labels.api_name
  - value: istio.io/service/client/response_bytes
    key: cloud.gcp.istio_io.service.client.response_bytes
    type: gauge
    name: Client Response Bytes
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: By
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
    - value: metric.labels.request_operation
    - value: metric.labels.api_version
    - value: metric.labels.response_code
    - value: metric.labels.api_name
  - value: istio.io/service/client/roundtrip_latencies
    key: cloud.gcp.istio_io.service.client.roundtrip_latencies
    type: gauge
    name: Client Roundtrip Latencies
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: ms
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
    - value: metric.labels.request_operation
    - value: metric.labels.api_version
    - value: metric.labels.response_code
    - value: metric.labels.api_name
  - value: istio.io/service/client/sent_bytes_count
    key: cloud.gcp.istio_io.service.client.sent_bytes_count
    type: count,delta
    name: Client Sent Bytes Count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: CUMULATIVE
      unit: By
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision