id: pubsub_subscription
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
- id: filter_conditions
  displayName: Metric query filter for which metrics should be queried
  type: variables
technology:
  name: Google Cloud Pub/Sub Subscription
gcp:
- service: pubsub_subscription
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: label:resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: label:resource.labels.project_id
    key: gcp.project.id
  - value: label:resource.labels.subscription_id
    key: subscription_id
    compatibilityModeOnly: true
  - value: label:resource.labels.subscription_id
    key: gcp.instance.id
  metrics:
  - value: metric:pubsub.googleapis.com/subscription/ack_message_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.ack_message_count
    type: count,delta
    name: Ack message count
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.delivery_type
      key: delivery_type
  - value: metric:pubsub.googleapis.com/subscription/backlog_bytes
    key: cloud.gcp.pubsub_googleapis_com.subscription.backlog_bytes
    type: gauge
    name: Backlog size
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: By
    dimensions: []
  - value: metric:pubsub.googleapis.com/subscription/byte_cost
    key: cloud.gcp.pubsub_googleapis_com.subscription.byte_cost
    type: count,delta
    name: Subscription byte cost
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: label:metric.labels.operation_type
      key: operation_type
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:pubsub.googleapis.com/subscription/config_updates_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.config_updates_count
    type: count,delta
    name: Subscription updates
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_code
      key: response_code
    - value: label:metric.labels.operation_type
      key: operation_type
  - value: metric:pubsub.googleapis.com/subscription/dead_letter_message_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.dead_letter_message_count
    type: count,delta
    name: Dead letter message count
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:pubsub.googleapis.com/subscription/mod_ack_deadline_message_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.mod_ack_deadline_message_count
    type: count,delta
    name: Mod ack deadline message count
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.delivery_type
      key: delivery_type
  - value: metric:pubsub.googleapis.com/subscription/mod_ack_deadline_message_operation_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.mod_ack_deadline_message_operation_count
    type: count,delta
    name: ModifyAckDeadline message operations
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:pubsub.googleapis.com/subscription/mod_ack_deadline_request_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.mod_ack_deadline_request_count
    type: count,delta
    name: ModifyAckDeadline requests
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_class
      key: response_class
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:pubsub.googleapis.com/subscription/num_outstanding_messages
    key: cloud.gcp.pubsub_googleapis_com.subscription.num_outstanding_messages
    type: gauge
    name: Outstanding push messages
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: metric:pubsub.googleapis.com/subscription/num_retained_acked_messages
    key: cloud.gcp.pubsub_googleapis_com.subscription.num_retained_acked_messages
    type: gauge
    name: Retained acked messages
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: metric:pubsub.googleapis.com/subscription/num_retained_acked_messages_by_region
    key: cloud.gcp.pubsub_googleapis_com.subscription.num_retained_acked_messages_by_region
    type: gauge
    name: Retained acked messages by region
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.region
      compatibilityModeOnly: true
      key: region
    - value: label:metric.labels.region
      key: region
  - value: metric:pubsub.googleapis.com/subscription/num_unacked_messages_by_region
    key: cloud.gcp.pubsub_googleapis_com.subscription.num_unacked_messages_by_region
    type: gauge
    name: Unacked messages by region
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.region
      compatibilityModeOnly: true
      key: region
    - value: label:metric.labels.region
      key: region
  - value: metric:pubsub.googleapis.com/subscription/num_undelivered_messages
    key: cloud.gcp.pubsub_googleapis_com.subscription.num_undelivered_messages
    type: gauge
    name: Unacked messages
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: metric:pubsub.googleapis.com/subscription/oldest_retained_acked_message_age
    key: cloud.gcp.pubsub_googleapis_com.subscription.oldest_retained_acked_message_age
    type: gauge
    name: Oldest retained acked message age
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: s
    dimensions: []
  - value: metric:pubsub.googleapis.com/subscription/oldest_retained_acked_message_age_by_region
    key: cloud.gcp.pubsub_googleapis_com.subscription.oldest_retained_acked_message_age_by_region
    type: gauge
    name: Oldest retained acked message age by region
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: s
    dimensions:
    - value: label:metric.labels.region
      compatibilityModeOnly: true
      key: region
    - value: label:metric.labels.region
      key: region
  - value: metric:pubsub.googleapis.com/subscription/oldest_unacked_message_age
    key: cloud.gcp.pubsub_googleapis_com.subscription.oldest_unacked_message_age
    type: gauge
    name: Oldest unacked message age
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: s
    dimensions: []
  - value: metric:pubsub.googleapis.com/subscription/oldest_unacked_message_age_by_region
    key: cloud.gcp.pubsub_googleapis_com.subscription.oldest_unacked_message_age_by_region
    type: gauge
    name: Oldest unacked message age by region
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: s
    dimensions:
    - value: label:metric.labels.region
      compatibilityModeOnly: true
      key: region
    - value: label:metric.labels.region
      key: region
  - value: metric:pubsub.googleapis.com/subscription/pull_ack_message_operation_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.pull_ack_message_operation_count
    type: count,delta
    name: Acknowledge message operations
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:pubsub.googleapis.com/subscription/pull_ack_request_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.pull_ack_request_count
    type: count,delta
    name: Acknowledge requests
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_class
      key: response_class
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:pubsub.googleapis.com/subscription/pull_message_operation_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.pull_message_operation_count
    type: count,delta
    name: Pull operations
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:pubsub.googleapis.com/subscription/pull_request_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.pull_request_count
    type: count,delta
    name: Pull requests
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_class
      key: response_class
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:pubsub.googleapis.com/subscription/push_request_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.push_request_count
    type: count,delta
    name: Push requests
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_class
      key: response_class
    - value: label:metric.labels.response_code
      key: response_code
    - value: label:metric.labels.delivery_type
      key: delivery_type
  - value: metric:pubsub.googleapis.com/subscription/push_request_latencies
    key: cloud.gcp.pubsub_googleapis_com.subscription.push_request_latencies
    type: gauge
    name: Push latency
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: us
    dimensions:
    - value: label:metric.labels.response_code
      key: response_code
    - value: label:metric.labels.delivery_type
      key: delivery_type
  - value: metric:pubsub.googleapis.com/subscription/retained_acked_bytes
    key: cloud.gcp.pubsub_googleapis_com.subscription.retained_acked_bytes
    type: gauge
    name: Retained acked bytes
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: By
    dimensions: []
  - value: metric:pubsub.googleapis.com/subscription/retained_acked_bytes_by_region
    key: cloud.gcp.pubsub_googleapis_com.subscription.retained_acked_bytes_by_region
    type: gauge
    name: Retained acked bytes by region
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: By
    dimensions:
    - value: label:metric.labels.region
      compatibilityModeOnly: true
      key: region
    - value: label:metric.labels.region
      key: region
  - value: metric:pubsub.googleapis.com/subscription/seek_request_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.seek_request_count
    type: count,delta
    name: Seek requests
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:pubsub.googleapis.com/subscription/sent_message_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.sent_message_count
    type: count,delta
    name: Sent message count
    gcpOptions:
      ingestDelay: 240
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.delivery_type
      key: delivery_type
  - value: metric:pubsub.googleapis.com/subscription/streaming_pull_ack_message_operation_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.streaming_pull_ack_message_operation_count
    type: count,delta
    name: StreamingPull Acknowledge message operations
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:pubsub.googleapis.com/subscription/streaming_pull_ack_request_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.streaming_pull_ack_request_count
    type: count,delta
    name: StreamingPull Acknowledge requests
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_class
      key: response_class
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:pubsub.googleapis.com/subscription/streaming_pull_message_operation_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.streaming_pull_message_operation_count
    type: count,delta
    name: StreamingPull message operations
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:pubsub.googleapis.com/subscription/streaming_pull_mod_ack_deadline_message_operation_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.streaming_pull_mod_ack_deadline_message_operation_count
    type: count,delta
    name: StreamingPull ModifyAckDeadline message operations
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:pubsub.googleapis.com/subscription/streaming_pull_mod_ack_deadline_request_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.streaming_pull_mod_ack_deadline_request_count
    type: count,delta
    name: StreamingPull ModifyAckDeadline requests
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_class
      key: response_class
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:pubsub.googleapis.com/subscription/streaming_pull_response_count
    key: cloud.gcp.pubsub_googleapis_com.subscription.streaming_pull_response_count
    type: count,delta
    name: StreamingPull responses
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.response_class
      key: response_class
    - value: label:metric.labels.response_code
      key: response_code
  - value: metric:pubsub.googleapis.com/subscription/unacked_bytes_by_region
    key: cloud.gcp.pubsub_googleapis_com.subscription.unacked_bytes_by_region
    type: gauge
    name: Unacked bytes by region
    gcpOptions:
      ingestDelay: 120
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: By
    dimensions:
    - value: label:metric.labels.region
      compatibilityModeOnly: true
      key: region
    - value: label:metric.labels.region
      key: region
dashboards:
- dashboard: dashboards/pubsub.json
