id: pubsub_subscription
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud Pub/Sub Subscription
gcp:
- service: pubsub_subscription
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.subscription_id
    id: subscription_id
    compatibilityModeOnly: true
  - value: resource.labels.subscription_id
    id: gcp.instance.id
  metrics:
  - value: pubsub.googleapis.com/subscription/ack_message_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.ack_message_count
    type: count,delta
    name: Ack message count
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.delivery_type
  - value: pubsub.googleapis.com/subscription/backlog_bytes
    id: cloud.gcp.pubsub_googleapis_com.subscription.backlog_bytes
    type: gauge
    name: Backlog size
    unit: By
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: pubsub.googleapis.com/subscription/byte_cost
    id: cloud.gcp.pubsub_googleapis_com.subscription.byte_cost
    type: count,delta
    name: Subscription byte cost
    unit: By
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.operation_type
    - value: metric.labels.response_code
  - value: pubsub.googleapis.com/subscription/config_updates_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.config_updates_count
    type: count,delta
    name: Subscription updates
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
    - value: metric.labels.operation_type
  - value: pubsub.googleapis.com/subscription/dead_letter_message_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.dead_letter_message_count
    type: count,delta
    name: Dead letter message count
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
  - value: pubsub.googleapis.com/subscription/mod_ack_deadline_message_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.mod_ack_deadline_message_count
    type: count,delta
    name: Mod ack deadline message count
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.delivery_type
  - value: pubsub.googleapis.com/subscription/mod_ack_deadline_message_operation_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.mod_ack_deadline_message_operation_count
    type: count,delta
    name: ModifyAckDeadline message operations
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
  - value: pubsub.googleapis.com/subscription/mod_ack_deadline_request_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.mod_ack_deadline_request_count
    type: count,delta
    name: ModifyAckDeadline requests
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_class
    - value: metric.labels.response_code
  - value: pubsub.googleapis.com/subscription/num_outstanding_messages
    id: cloud.gcp.pubsub_googleapis_com.subscription.num_outstanding_messages
    type: gauge
    name: Outstanding push messages
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: pubsub.googleapis.com/subscription/num_retained_acked_messages
    id: cloud.gcp.pubsub_googleapis_com.subscription.num_retained_acked_messages
    type: gauge
    name: Retained acked messages
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: pubsub.googleapis.com/subscription/num_retained_acked_messages_by_region
    id: cloud.gcp.pubsub_googleapis_com.subscription.num_retained_acked_messages_by_region
    type: gauge
    name: Retained acked messages by region
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.region
      compatibilityModeOnly: true
    - value: metric.labels.region
      id: gcp.region
  - value: pubsub.googleapis.com/subscription/num_unacked_messages_by_region
    id: cloud.gcp.pubsub_googleapis_com.subscription.num_unacked_messages_by_region
    type: gauge
    name: Unacked messages by region
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.region
      compatibilityModeOnly: true
    - value: metric.labels.region
      id: gcp.region
  - value: pubsub.googleapis.com/subscription/num_undelivered_messages
    id: cloud.gcp.pubsub_googleapis_com.subscription.num_undelivered_messages
    type: gauge
    name: Unacked messages
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: pubsub.googleapis.com/subscription/oldest_retained_acked_message_age
    id: cloud.gcp.pubsub_googleapis_com.subscription.oldest_retained_acked_message_age
    type: gauge
    name: Oldest retained acked message age
    unit: s
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: pubsub.googleapis.com/subscription/oldest_retained_acked_message_age_by_region
    id: cloud.gcp.pubsub_googleapis_com.subscription.oldest_retained_acked_message_age_by_region
    type: gauge
    name: Oldest retained acked message age by region
    unit: s
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.region
      compatibilityModeOnly: true
    - value: metric.labels.region
      id: gcp.region
  - value: pubsub.googleapis.com/subscription/oldest_unacked_message_age
    id: cloud.gcp.pubsub_googleapis_com.subscription.oldest_unacked_message_age
    type: gauge
    name: Oldest unacked message age
    unit: s
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: pubsub.googleapis.com/subscription/oldest_unacked_message_age_by_region
    id: cloud.gcp.pubsub_googleapis_com.subscription.oldest_unacked_message_age_by_region
    type: gauge
    name: Oldest unacked message age by region
    unit: s
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.region
      compatibilityModeOnly: true
    - value: metric.labels.region
      id: gcp.region
  - value: pubsub.googleapis.com/subscription/pull_ack_message_operation_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.pull_ack_message_operation_count
    type: count,delta
    name: Acknowledge message operations
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
  - value: pubsub.googleapis.com/subscription/pull_ack_request_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.pull_ack_request_count
    type: count,delta
    name: Acknowledge requests
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_class
    - value: metric.labels.response_code
  - value: pubsub.googleapis.com/subscription/pull_message_operation_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.pull_message_operation_count
    type: count,delta
    name: Pull operations
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
  - value: pubsub.googleapis.com/subscription/pull_request_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.pull_request_count
    type: count,delta
    name: Pull requests
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_class
    - value: metric.labels.response_code
  - value: pubsub.googleapis.com/subscription/push_request_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.push_request_count
    type: count,delta
    name: Push requests
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_class
    - value: metric.labels.response_code
    - value: metric.labels.delivery_type
  - value: pubsub.googleapis.com/subscription/push_request_latencies
    id: cloud.gcp.pubsub_googleapis_com.subscription.push_request_latencies
    type: gauge
    name: Push latency
    unit: us
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
    - value: metric.labels.delivery_type
  - value: pubsub.googleapis.com/subscription/retained_acked_bytes
    id: cloud.gcp.pubsub_googleapis_com.subscription.retained_acked_bytes
    type: gauge
    name: Retained acked bytes
    unit: By
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: pubsub.googleapis.com/subscription/retained_acked_bytes_by_region
    id: cloud.gcp.pubsub_googleapis_com.subscription.retained_acked_bytes_by_region
    type: gauge
    name: Retained acked bytes by region
    unit: By
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.region
      compatibilityModeOnly: true
    - value: metric.labels.region
      id: gcp.region
  - value: pubsub.googleapis.com/subscription/seek_request_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.seek_request_count
    type: count,delta
    name: Seek requests
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
  - value: pubsub.googleapis.com/subscription/sent_message_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.sent_message_count
    type: count,delta
    name: Sent message count
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.delivery_type
  - value: pubsub.googleapis.com/subscription/streaming_pull_ack_message_operation_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.streaming_pull_ack_message_operation_count
    type: count,delta
    name: StreamingPull Acknowledge message operations
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
  - value: pubsub.googleapis.com/subscription/streaming_pull_ack_request_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.streaming_pull_ack_request_count
    type: count,delta
    name: StreamingPull Acknowledge requests
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_class
    - value: metric.labels.response_code
  - value: pubsub.googleapis.com/subscription/streaming_pull_message_operation_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.streaming_pull_message_operation_count
    type: count,delta
    name: StreamingPull message operations
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
  - value: pubsub.googleapis.com/subscription/streaming_pull_mod_ack_deadline_message_operation_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.streaming_pull_mod_ack_deadline_message_operation_count
    type: count,delta
    name: StreamingPull ModifyAckDeadline message operations
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
  - value: pubsub.googleapis.com/subscription/streaming_pull_mod_ack_deadline_request_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.streaming_pull_mod_ack_deadline_request_count
    type: count,delta
    name: StreamingPull ModifyAckDeadline requests
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_class
    - value: metric.labels.response_code
  - value: pubsub.googleapis.com/subscription/streaming_pull_response_count
    id: cloud.gcp.pubsub_googleapis_com.subscription.streaming_pull_response_count
    type: count,delta
    name: StreamingPull responses
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_class
    - value: metric.labels.response_code
  - value: pubsub.googleapis.com/subscription/unacked_bytes_by_region
    id: cloud.gcp.pubsub_googleapis_com.subscription.unacked_bytes_by_region
    type: gauge
    name: Unacked bytes by region
    unit: By
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.region
      compatibilityModeOnly: true
    - value: metric.labels.region
      id: gcp.region
dashboards:
  - dashboard: "dashboards/pubsub.json"