id: redis_instance
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud Memorystore
gcp:
- service: redis_instance
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.region
    id: region
    compatibilityModeOnly: true
  - value: resource.labels.region
    id: gcp.region
  - value: resource.labels.instance_id
    id: instance_id
    compatibilityModeOnly: true
  - value: resource.labels.instance_id
    id: gcp.instance.id
  - value: resource.labels.node_id
    id: node_id
  metrics:
  - value: redis.googleapis.com/clients/blocked
    id: cloud.gcp.redis_googleapis_com.clients.blocked
    type: gauge
    name: Blocked Clients
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/clients/connected
    id: cloud.gcp.redis_googleapis_com.clients.connected
    type: gauge
    name: Connected Clients
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/commands/calls
    id: cloud.gcp.redis_googleapis_com.commands.calls
    type: count,delta
    name: Calls
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.role
    - value: metric.labels.cmd
  - value: redis.googleapis.com/commands/total_time
    id: cloud.gcp.redis_googleapis_com.commands.total_time
    type: count,delta
    name: Total Time of Calls
    unit: us
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.role
    - value: metric.labels.cmd
  - value: redis.googleapis.com/commands/usec_per_call
    id: cloud.gcp.redis_googleapis_com.commands.usec_per_call
    type: gauge
    name: Time per Call
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
    - value: metric.labels.cmd
  - value: redis.googleapis.com/keyspace/avg_ttl
    id: cloud.gcp.redis_googleapis_com.keyspace.avg_ttl
    type: gauge
    name: Average TTL
    unit: ms
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
    - value: metric.labels.db
  - value: redis.googleapis.com/keyspace/keys
    id: cloud.gcp.redis_googleapis_com.keyspace.keys
    type: gauge
    name: Keys
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
    - value: metric.labels.db
  - value: redis.googleapis.com/keyspace/keys_with_expiration
    id: cloud.gcp.redis_googleapis_com.keyspace.keys_with_expiration
    type: gauge
    name: Expirable Keys
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
    - value: metric.labels.db
  - value: redis.googleapis.com/persistence/rdb/bgsave_in_progress
    id: cloud.gcp.redis_googleapis_com.persistence.rdb.bgsave_in_progress
    type: gauge
    name: Persisting RDB
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: BOOL
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/replication/master/slaves/lag
    id: cloud.gcp.redis_googleapis_com.replication.master.slaves.lag
    type: gauge
    name: Bytes lagging
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
    - value: metric.labels.slave
  - value: redis.googleapis.com/replication/master/slaves/offset
    id: cloud.gcp.redis_googleapis_com.replication.master.slaves.offset
    type: gauge
    name: Replication byte offset (Replica)
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
    - value: metric.labels.slave
  - value: redis.googleapis.com/replication/master_repl_offset
    id: cloud.gcp.redis_googleapis_com.replication.master_repl_offset
    type: gauge
    name: Replication byte offset (Master)
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/replication/offset_diff
    id: cloud.gcp.redis_googleapis_com.replication.offset_diff
    type: gauge
    name: Bytes pending replication
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/replication/role
    id: cloud.gcp.redis_googleapis_com.replication.role
    type: gauge
    name: Node Role
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: redis.googleapis.com/server/uptime
    id: cloud.gcp.redis_googleapis_com.server.uptime
    type: gauge
    name: Uptime
    unit: s
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/stats/cache_hit_ratio
    id: cloud.gcp.redis_googleapis_com.stats.cache_hit_ratio
    type: gauge
    name: Cache Hit ratio
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/stats/connections/total
    id: cloud.gcp.redis_googleapis_com.stats.connections.total
    type: count,delta
    name: Total Connections Received
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/stats/cpu_utilization
    id: cloud.gcp.redis_googleapis_com.stats.cpu_utilization
    type: count,delta
    name: CPU seconds
    unit: s{CPU}
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions:
    - value: metric.labels.role
    - value: metric.labels.space
    - value: metric.labels.relationship
  - value: redis.googleapis.com/stats/evicted_keys
    id: cloud.gcp.redis_googleapis_com.stats.evicted_keys
    type: count,delta
    name: Evicted Keys
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/stats/expired_keys
    id: cloud.gcp.redis_googleapis_com.stats.expired_keys
    type: count,delta
    name: Expired Keys
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/stats/keyspace_hits
    id: cloud.gcp.redis_googleapis_com.stats.keyspace_hits
    type: count,delta
    name: Hits
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/stats/keyspace_misses
    id: cloud.gcp.redis_googleapis_com.stats.keyspace_misses
    type: count,delta
    name: Misses
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/stats/memory/maxmemory
    id: cloud.gcp.redis_googleapis_com.stats.memory.maxmemory
    type: gauge
    name: Maximum Memory
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/stats/memory/system_memory_overload_duration
    id: cloud.gcp.redis_googleapis_com.stats.memory.system_memory_overload_duration
    type: count,delta
    name: Time in system memory overload
    unit: us
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/stats/memory/system_memory_usage_ratio
    id: cloud.gcp.redis_googleapis_com.stats.memory.system_memory_usage_ratio
    type: gauge
    name: System Memory Usage Ratio
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/stats/memory/usage
    id: cloud.gcp.redis_googleapis_com.stats.memory.usage
    type: gauge
    name: Used Memory
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/stats/memory/usage_ratio
    id: cloud.gcp.redis_googleapis_com.stats.memory.usage_ratio
    type: gauge
    name: Memory Usage Ratio
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/stats/network_traffic
    id: cloud.gcp.redis_googleapis_com.stats.network_traffic
    type: count,delta
    name: Total traffic to Redis
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.role
    - value: metric.labels.direction
  - value: redis.googleapis.com/stats/pubsub/channels
    id: cloud.gcp.redis_googleapis_com.stats.pubsub.channels
    type: gauge
    name: Pubsub Channels
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/stats/pubsub/patterns
    id: cloud.gcp.redis_googleapis_com.stats.pubsub.patterns
    type: gauge
    name: Pubsub Patterns
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.role
  - value: redis.googleapis.com/stats/reject_connections_count
    id: cloud.gcp.redis_googleapis_com.stats.reject_connections_count
    type: count,delta
    name: Rejected Connections
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.role
