id: redis_instance
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
- id: filter_conditions
  displayName: Metric query filter for which metrics should be queried
  type: variables
technology:
  name: Google Cloud Memorystore
gcp:
- service: redis_instance
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: label:resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: label:resource.labels.project_id
    key: gcp.project.id
  - value: label:resource.labels.region
    key: region
    compatibilityModeOnly: true
  - value: label:resource.labels.region
    key: gcp.region
  - value: label:resource.labels.instance_id
    key: instance_id
    compatibilityModeOnly: true
  - value: label:resource.labels.instance_id
    key: gcp.instance.id
  - value: label:resource.labels.node_id
    key: node_id
  metrics:
  - value: metric:redis.googleapis.com/clients/blocked
    key: cloud.gcp.redis_googleapis_com.clients.blocked
    type: gauge
    name: Blocked Clients
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/clients/connected
    key: cloud.gcp.redis_googleapis_com.clients.connected
    type: gauge
    name: Connected Clients
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/commands/calls
    key: cloud.gcp.redis_googleapis_com.commands.calls
    type: count,delta
    name: Calls
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
    - value: label:metric.labels.cmd
      key: cmd
  - value: metric:redis.googleapis.com/commands/total_time
    key: cloud.gcp.redis_googleapis_com.commands.total_time
    type: count,delta
    name: Total Time of Calls
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: us
    dimensions:
    - value: label:metric.labels.role
      key: role
    - value: label:metric.labels.cmd
      key: cmd
  - value: metric:redis.googleapis.com/commands/usec_per_call
    key: cloud.gcp.redis_googleapis_com.commands.usec_per_call
    type: gauge
    name: Time per Call
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
    - value: label:metric.labels.cmd
      key: cmd
  - value: metric:redis.googleapis.com/keyspace/avg_ttl
    key: cloud.gcp.redis_googleapis_com.keyspace.avg_ttl
    type: gauge
    name: Average TTL
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: ms
    dimensions:
    - value: label:metric.labels.role
      key: role
    - value: label:metric.labels.db
      key: db
  - value: metric:redis.googleapis.com/keyspace/keys
    key: cloud.gcp.redis_googleapis_com.keyspace.keys
    type: gauge
    name: Keys
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
    - value: label:metric.labels.db
      key: db
  - value: metric:redis.googleapis.com/keyspace/keys_with_expiration
    key: cloud.gcp.redis_googleapis_com.keyspace.keys_with_expiration
    type: gauge
    name: Expirable Keys
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
    - value: label:metric.labels.db
      key: db
  - value: metric:redis.googleapis.com/persistence/rdb/bgsave_in_progress
    key: cloud.gcp.redis_googleapis_com.persistence.rdb.bgsave_in_progress
    type: gauge
    name: Persisting RDB
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: BOOL
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/replication/master/slaves/lag
    key: cloud.gcp.redis_googleapis_com.replication.master.slaves.lag
    type: gauge
    name: Bytes lagging
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: By
    dimensions:
    - value: label:metric.labels.role
      key: role
    - value: label:metric.labels.slave
      key: slave
  - value: metric:redis.googleapis.com/replication/master/slaves/offset
    key: cloud.gcp.redis_googleapis_com.replication.master.slaves.offset
    type: gauge
    name: Replication byte offset (Replica)
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: By
    dimensions:
    - value: label:metric.labels.role
      key: role
    - value: label:metric.labels.slave
      key: slave
  - value: metric:redis.googleapis.com/replication/master_repl_offset
    key: cloud.gcp.redis_googleapis_com.replication.master_repl_offset
    type: gauge
    name: Replication byte offset (Master)
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: By
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/replication/offset_diff
    key: cloud.gcp.redis_googleapis_com.replication.offset_diff
    type: gauge
    name: Bytes pending replication
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: By
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/replication/role
    key: cloud.gcp.redis_googleapis_com.replication.role
    type: gauge
    name: Node Role
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: metric:redis.googleapis.com/server/uptime
    key: cloud.gcp.redis_googleapis_com.server.uptime
    type: gauge
    name: Uptime
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: s
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/stats/cache_hit_ratio
    key: cloud.gcp.redis_googleapis_com.stats.cache_hit_ratio
    type: gauge
    name: Cache Hit ratio
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/stats/connections/total
    key: cloud.gcp.redis_googleapis_com.stats.connections.total
    type: count,delta
    name: Total Connections Received
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/stats/cpu_utilization
    key: cloud.gcp.redis_googleapis_com.stats.cpu_utilization
    type: count,delta
    name: CPU seconds
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: DELTA
      unit: s{CPU}
    dimensions:
    - value: label:metric.labels.role
      key: role
    - value: label:metric.labels.space
      key: space
    - value: label:metric.labels.relationship
      key: relationship
  - value: metric:redis.googleapis.com/stats/evicted_keys
    key: cloud.gcp.redis_googleapis_com.stats.evicted_keys
    type: count,delta
    name: Evicted Keys
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/stats/expired_keys
    key: cloud.gcp.redis_googleapis_com.stats.expired_keys
    type: count,delta
    name: Expired Keys
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/stats/keyspace_hits
    key: cloud.gcp.redis_googleapis_com.stats.keyspace_hits
    type: count,delta
    name: Hits
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/stats/keyspace_misses
    key: cloud.gcp.redis_googleapis_com.stats.keyspace_misses
    type: count,delta
    name: Misses
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/stats/memory/maxmemory
    key: cloud.gcp.redis_googleapis_com.stats.memory.maxmemory
    type: gauge
    name: Maximum Memory
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: By
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/stats/memory/system_memory_overload_duration
    key: cloud.gcp.redis_googleapis_com.stats.memory.system_memory_overload_duration
    type: count,delta
    name: Time in system memory overload
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: us
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/stats/memory/system_memory_usage_ratio
    key: cloud.gcp.redis_googleapis_com.stats.memory.system_memory_usage_ratio
    type: gauge
    name: System Memory Usage Ratio
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/stats/memory/usage
    key: cloud.gcp.redis_googleapis_com.stats.memory.usage
    type: gauge
    name: Used Memory
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: By
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/stats/memory/usage_ratio
    key: cloud.gcp.redis_googleapis_com.stats.memory.usage_ratio
    type: gauge
    name: Memory Usage Ratio
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/stats/network_traffic
    key: cloud.gcp.redis_googleapis_com.stats.network_traffic
    type: count,delta
    name: Total traffic to Redis
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: label:metric.labels.role
      key: role
    - value: label:metric.labels.direction
      key: direction
  - value: metric:redis.googleapis.com/stats/pubsub/channels
    key: cloud.gcp.redis_googleapis_com.stats.pubsub.channels
    type: gauge
    name: Pubsub Channels
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/stats/pubsub/patterns
    key: cloud.gcp.redis_googleapis_com.stats.pubsub.patterns
    type: gauge
    name: Pubsub Patterns
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
  - value: metric:redis.googleapis.com/stats/reject_connections_count
    key: cloud.gcp.redis_googleapis_com.stats.reject_connections_count
    type: count,delta
    name: Rejected Connections
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.role
      key: role
