id: tcp_lb_rule
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
- id: filter_conditions
  displayName: Metric query filter for which metrics should be queried
  type: variables
technology:
  name: Google Cloud Network TCP Load Balancer Rule
gcp:
- service: tcp_lb_rule
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: label:resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: label:resource.labels.project_id
    key: gcp.project.id
  - value: label:resource.labels.load_balancer_name
    key: load_balancer_name
    compatibilityModeOnly: true
  - value: label:resource.labels.load_balancer_name
    key: gcp.instance.name
  - value: label:resource.labels.region
    key: region
    compatibilityModeOnly: true
  - value: label:resource.labels.region
    key: gcp.region
  - value: label:resource.labels.network_name
    key: network_name
  - value: label:resource.labels.backend_target_type
    key: backend_target_type
  - value: label:resource.labels.backend_target_name
    key: backend_target_name
  - value: label:resource.labels.forwarding_rule_name
    key: forwarding_rule_name
  - value: label:resource.labels.forwarding_rule_network_tier
    key: forwarding_rule_network_tier
  - value: label:resource.labels.backend_name
    key: backend_name
  - value: label:resource.labels.backend_type
    key: backend_type
  - value: label:resource.labels.backend_scope
    key: backend_scope
  - value: label:resource.labels.backend_scope_type
    key: backend_scope_type
  - value: label:resource.labels.backend_failover_configuration
    key: backend_failover_configuration
  - value: label:resource.labels.backend_subnetwork_name
    key: backend_subnetwork_name
  - value: label:resource.labels.endpoint_zone
    key: endpoint_zone
  metrics:
  - value: metric:loadbalancing.googleapis.com/l3/external/egress_bytes_count
    key: cloud.gcp.loadbalancing_googleapis_com.l3.external.egress_bytes_count
    type: count,delta
    name: Egress bytes
    gcpOptions:
      ingestDelay: 150
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: label:metric.labels.client_continent
      key: client_continent
    - value: label:metric.labels.client_country
      key: client_country
  - value: metric:loadbalancing.googleapis.com/l3/external/egress_packets_count
    key: cloud.gcp.loadbalancing_googleapis_com.l3.external.egress_packets_count
    type: count,delta
    name: Egress packets
    gcpOptions:
      ingestDelay: 150
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.client_continent
      key: client_continent
    - value: label:metric.labels.client_country
      key: client_country
  - value: metric:loadbalancing.googleapis.com/l3/external/ingress_bytes_count
    key: cloud.gcp.loadbalancing_googleapis_com.l3.external.ingress_bytes_count
    type: count,delta
    name: Ingress bytes
    gcpOptions:
      ingestDelay: 150
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: label:metric.labels.client_continent
      key: client_continent
    - value: label:metric.labels.client_country
      key: client_country
  - value: metric:loadbalancing.googleapis.com/l3/external/ingress_packets_count
    key: cloud.gcp.loadbalancing_googleapis_com.l3.external.ingress_packets_count
    type: count,delta
    name: Ingress packets
    gcpOptions:
      ingestDelay: 150
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.client_continent
      key: client_continent
    - value: label:metric.labels.client_country
      key: client_country
  - value: metric:loadbalancing.googleapis.com/l3/external/rtt_latencies
    key: cloud.gcp.loadbalancing_googleapis_com.l3.external.rtt_latencies
    type: gauge
    name: RTT latencies
    gcpOptions:
      ingestDelay: 150
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: ms
    dimensions:
    - value: label:metric.labels.client_continent
      key: client_continent
    - value: label:metric.labels.client_country
      key: client_country
dashboards:
- dashboard: dashboards/lb_tcp.json
