id: transfer_service_agent
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
- id: filter_conditions
  displayName: Metric query filter for which metrics should be queried
  type: variables
technology:
  name: Google Transfer Service Agent
gcp:
- service: transfer_service_agent
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: label:resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: label:resource.labels.project_id
    key: gcp.project.id
  - value: label:resource.labels.agent_id
    key: agent_id
    compatibilityModeOnly: true
  - value: label:resource.labels.agent_id
    key: gcp.instance.id
  metrics:
  - value: metric:storagetransfer.googleapis.com/agent/connected
    key: cloud.gcp.storagetransfer_googleapis_com.agent.connected
    type: gauge
    name: Agent connected status
    gcpOptions:
      ingestDelay: 60
      samplePeriod: 60
      valueType: BOOL
      metricKind: GAUGE
      unit: ''
    dimensions: []
  - value: metric:storagetransfer.googleapis.com/agent/transferred_bytes_count
    key: cloud.gcp.storagetransfer_googleapis_com.agent.transferred_bytes_count
    type: count,delta
    name: Agent transfer delta
    gcpOptions:
      ingestDelay: 60
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions: []
