id: vpn_gateway
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
- id: filter_conditions
  displayName: Metric query filter for which metrics should be queried
  type: variables
technology:
  name: Google Cloud VPN Tunnel
gcp:
- service: vpn_gateway
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: label:resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: label:resource.labels.project_id
    key: gcp.project.id
  - value: label:resource.labels.gateway_id
    key: gateway_id
    compatibilityModeOnly: true
  - value: label:resource.labels.gateway_id
    key: gcp.instance.id
  - value: label:resource.labels.region
    key: region
    compatibilityModeOnly: true
  - value: label:resource.labels.region
    key: gcp.region
  metrics:
  - value: metric:vpn.googleapis.com/gateway/connections
    key: cloud.gcp.vpn_googleapis_com.gateway.connections
    type: gauge
    name: Number of connections
    gcpOptions:
      ingestDelay: 60
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.configured_for_sla
      key: configured_for_sla
    - value: label:metric.labels.gcp_service_health
      key: gcp_service_health
    - value: label:metric.labels.end_to_end_health
      key: end_to_end_health
  - value: metric:vpn.googleapis.com/network/dropped_received_packets_count
    key: cloud.gcp.vpn_googleapis_com.network.dropped_received_packets_count
    type: count,delta
    name: Incoming packets dropped
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.tunnel_name
      key: tunnel_name
    - value: label:metric.labels.gateway_name
      key: gateway_name
      compatibilityModeOnly: true
    - value: label:metric.labels.gateway_name
      key: gateway_name
  - value: metric:vpn.googleapis.com/network/dropped_sent_packets_count
    key: cloud.gcp.vpn_googleapis_com.network.dropped_sent_packets_count
    type: count,delta
    name: Outgoing packets dropped
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: label:metric.labels.tunnel_name
      key: tunnel_name
    - value: label:metric.labels.gateway_name
      key: gateway_name
      compatibilityModeOnly: true
    - value: label:metric.labels.gateway_name
      key: gateway_name
  - value: metric:vpn.googleapis.com/network/received_bytes_count
    key: cloud.gcp.vpn_googleapis_com.network.received_bytes_count
    type: count,delta
    name: Received bytes
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: label:metric.labels.tunnel_name
      key: tunnel_name
    - value: label:metric.labels.gateway_name
      key: gateway_name
      compatibilityModeOnly: true
    - value: label:metric.labels.gateway_name
      key: gateway_name
  - value: metric:vpn.googleapis.com/network/received_packets_count
    key: cloud.gcp.vpn_googleapis_com.network.received_packets_count
    type: count,delta
    name: Received packets
    gcpOptions:
      ingestDelay: 60
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '{packets}'
    dimensions:
    - value: label:metric.labels.status
      key: status
    - value: label:metric.labels.tunnel_name
      key: tunnel_name
  - value: metric:vpn.googleapis.com/network/sent_bytes_count
    key: cloud.gcp.vpn_googleapis_com.network.sent_bytes_count
    type: count,delta
    name: Sent bytes
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions:
    - value: label:metric.labels.tunnel_name
      key: tunnel_name
    - value: label:metric.labels.gateway_name
      key: gateway_name
      compatibilityModeOnly: true
    - value: label:metric.labels.gateway_name
      key: gateway_name
  - value: metric:vpn.googleapis.com/network/sent_packets_count
    key: cloud.gcp.vpn_googleapis_com.network.sent_packets_count
    type: count,delta
    name: Sent packets
    gcpOptions:
      ingestDelay: 60
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '{packets}'
    dimensions:
    - value: label:metric.labels.status
      key: status
    - value: label:metric.labels.tunnel_name
      key: tunnel_name
  - value: metric:vpn.googleapis.com/tunnel_established
    key: cloud.gcp.vpn_googleapis_com.tunnel_established
    type: gauge
    name: Tunnel established
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: label:metric.labels.tunnel_name
      key: tunnel_name
    - value: label:metric.labels.gateway_name
      key: gateway_name
      compatibilityModeOnly: true
    - value: label:metric.labels.gateway_name
      key: gateway_name
