id: vpn_gateway
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud VPN Tunnel
gcp:
- service: vpn_gateway
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.gateway_id
    id: gateway_id
  - value: resource.labels.region
    id: region
  metrics:
  - value: vpn.googleapis.com/gateway/connections
    id: cloud.gcp.vpn_googleapis_com.gateway.connections
    type: gauge
    name: Number of connections
    unit: '1'
    gcpOptions:
      ingestDelay: 60s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.configured_for_sla
    - value: metric.labels.gcp_service_health
    - value: metric.labels.end_to_end_health
  - value: vpn.googleapis.com/network/dropped_received_packets_count
    id: cloud.gcp.vpn_googleapis_com.network.dropped_received_packets_count
    type: count,delta
    name: Incoming packets dropped
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.tunnel_name
    - value: metric.labels.gateway_name
  - value: vpn.googleapis.com/network/dropped_sent_packets_count
    id: cloud.gcp.vpn_googleapis_com.network.dropped_sent_packets_count
    type: count,delta
    name: Outgoing packets dropped
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.tunnel_name
    - value: metric.labels.gateway_name
  - value: vpn.googleapis.com/network/received_bytes_count
    id: cloud.gcp.vpn_googleapis_com.network.received_bytes_count
    type: count,delta
    name: Received bytes
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.tunnel_name
    - value: metric.labels.gateway_name
  - value: vpn.googleapis.com/network/received_packets_count
    id: cloud.gcp.vpn_googleapis_com.network.received_packets_count
    type: count,delta
    name: Received packets
    unit: '{packets}'
    gcpOptions:
      ingestDelay: 60s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.status
    - value: metric.labels.tunnel_name
  - value: vpn.googleapis.com/network/sent_bytes_count
    id: cloud.gcp.vpn_googleapis_com.network.sent_bytes_count
    type: count,delta
    name: Sent bytes
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.tunnel_name
    - value: metric.labels.gateway_name
  - value: vpn.googleapis.com/network/sent_packets_count
    id: cloud.gcp.vpn_googleapis_com.network.sent_packets_count
    type: count,delta
    name: Sent packets
    unit: '{packets}'
    gcpOptions:
      ingestDelay: 60s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.status
    - value: metric.labels.tunnel_name
  - value: vpn.googleapis.com/tunnel_established
    id: cloud.gcp.vpn_googleapis_com.tunnel_established
    type: gauge
    name: Tunnel established
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.tunnel_name
    - value: metric.labels.gateway_name
