autodicovery_config:
  searched_resources:
  # Google AI Platform
  # - cloudml_model_version
  # - cloudml_job
  # Google AlloyDB
  # - alloydb.googleapis.com/Instance
  # - alloydb.googleapis.com/Database
  # Google Cloud APIs
  # - api
  # - consumer_quota
  # - producer_quota
  # - consumed_api
  # - produced_api
  # Google Apigee
  # - apigee.googleapis.com/ProxyV2
  # - apigee.googleapis.com/Environment
  # - apigee.googleapis.com/Proxy
  # - apigee.googleapis.com/TargetV2
  # Google App Engine
  # - gae_instance
  # - gae_app
  # Google Assistant Smart Home
  # - assistant_action_project
  # Google BigQuery
  # - bigquery_biengine_model
  # - bigquery_project
  # - global
  # Google Cloud Bigtable
  # - bigtable_table
  # - bigtable_cluster
  # Google Cloud DNS
  # - dns_query
  # Google Cloud Functions
  # - cloud_function
  # Google Cloud IoT Core
  # - cloudiot_device_registry
  # Google Cloud Router
  # - nat_gateway
  # Google Cloud Run.
  # - cloud_run_revision
  # - cloud_run_job
  # Google Cloud Storage
  # - gcs_bucket
  # Google Cloud Tasks
  # - cloud_tasks_queue
  # Google Cloud Composer
  # - cloud_composer_environment
  # Google Compute Engine
  - instance_group
  - gce_instance
  - aws_ec2_instance
  - tpu_worker
  - autoscaler
  - baremetalsolution.googleapis.com/Instance
  # Google Cloud Storage Transfer
  # - transfer_service_agent
  # Google Dataflow
  # - dataflow_job
  # Google Dataproc
  # - cloud_dataproc_cluster
  # Google Firestore in Datastore mode
  # - datastore_request
  # Google Cloud Data Loss Prevention
  # - cloud_dlp_project
  # Google Cloud Filestore
  # - filestore_instance
  # Google Firebase
  # - firebase_domain
  # - firebase_namespace
  # Google Cloud Firestore
  # - firestore.googleapis.com/Database
  # - firestore_instance
  # Google Hybrid Connectivity
  # - interconnect
  # - vpn_gateway
  # - interconnect_attachment
  # - gce_router
  # Google Kubernetes Engine (GKE)
  #  - istio_control_plane
  # - k8s_node
  # - k8s_pod
  # - k8s_container
  # Google Cloud Load Balancing
  # - loadbalancing.googleapis.com/ExternalNetworkLoadBalancerRule
  # - udp_lb_rule
  # - internal_tcp_lb_rule
  # - internal_http_lb_rule
  # - internal_udp_lb_rule
  # - tcp_lb_rule
  # - https_lb_rule
  # - tcp_ssl_proxy_rule
  # Google Managed Microsoft AD
  # - microsoft_ad_domain
  # Google Memorystore
  # - redis_instance
  # NetApp on Google Cloud
  # - netapp_cloud_volume
  # - cloudvolumesgcp-api.netapp.com/CloudVolume
  # Google Network Security
  # - network_security_policy
  # Google Cloud's operations suite (disabled)
  #  servicedirectory_service
  #  k8s_service
  #  logging_sink
  #  aws_elb_load_balancer
  #  aws_ec2_instance
  #  gae_app
  #  cloud_run_revision
  #  cloudtrace.googleapis.com/CloudtraceProject
  #  gce_instance
  #  uptime_url
  # Google Pub/Sub
  # - pubsub_snapshot
  # - pubsub_subscription
  # - pubsub_topic
  # Google Pub/Sub Lite
  # - pubsublite_subscription_partition
  # - pubsublite_topic_partition
  # Google reCAPTCHA Enterprise
  # - recaptchaenterprise.googleapis.com/Key
  # Google Cloud Spanner
  # - spanner_instance
  # Google Cloud SQL
  # - cloudsql_database
  # - cloudsql_instance_database
  # Google Virtual Private Cloud
  # - vpc_access_connector
  # Google Network Topology
  # - gce_zone_network_health